### PR TITLE
Avoid duplicated SWNAMES in to auto-generated CLI output

### PR DESCRIPTION
**Pull request by wilzbach**
From https://github.com/dlang/dlang.org/pull/2068#issuecomment-363652740

Not so sure whether's really worth bother though.

### CODE REVIEW

**Comment by CyberShadow** [comment]
Thanks. Considering this is one step closer to generating pedantically correct HTML, I think it is.

**Comment by wilzbach** [comment]
And it's also closer to the non-generated version...

**Comment by CyberShadow** [comment]
(An alternative to not emitting them would be to make them unique)

**Comment by wilzbach** [comment]
(Yes, but then I would have needed to modify the SWNAME macro - not impossible, but resulting in a larger diff. I was torn between both approaches and ultimately went with this one because of the smaller diff and being closer to the "original")

**Pull request merged**
