### PR TITLE
css: Enforce input/textarea background only on dlang.org

### PR DESCRIPTION
**Pull request by CyberShadow**
Hotfix for forum.dlang.org.

### CODE REVIEW

**Comment by wilzbach** [comment]
Interestingly this also affected the runnable examples, but I actually like the new CSS a lot more :)

image

image

Before:

image

**Comment by CyberShadow** [comment]
Err. Hmm. CSS specficity shenanigans?

Note that it might look that way only in your browser.

**Comment by wilzbach** [comment]
> Err. Hmm. CSS specficity shenanigans?

More "precise" selectors have a higher priority.

image

**Comment by CyberShadow** [comment]
Yeah, specificity is actually the official term I think :) My guess was correct then?

**Pull request merged**
