### PR TITLE
Fix Issue 17680 - Broken ddmd source links in documentation

### PR DESCRIPTION
**Pull request by CyberShadow**

### CODE REVIEW

**Comment by CyberShadow** [comment]
@wilzbach Why is @dlang-bot giving me the regression warning even though the issue is neither critical nor a regression?

**Comment by CyberShadow** [comment]
```
Fetching libdparse 0.7.0-beta.7 (getting selected version)...
Timeout was reached on handle E114E0
```

Gosh darn it guys

**Comment by wilzbach** [comment]
> @wilzbach Why is @dlang-bot giving me the regression warning even though the issue is neither critical nor a regression?

Because "major" is part of the list:
https://github.com/dlang-bots/dlang-bot/blob/master/source/dlangbot/warnings.d

**Comment by CyberShadow** [comment]
Thanks.

**Comment by wilzbach** [comment]
Btw did you see https://github.com/dlang/dlang.org/pull/1843?

**Comment by CyberShadow** [comment]
Heh, no.

Please post a link to the PR in the issue you're fixing next time.

**Comment by wilzbach** [comment]
> Please post a link to the PR in the issue you're fixing next time.

Yeah I usually do, but I felt asleep shortly after that one. Sorry ;-)

**Pull request closed without merging**
