### PR TITLE
We use & support D since 2016 in our software and in SDK

### PR DESCRIPTION
**Pull request by PELock**
We use D in our server software, we also support D executables in our software protection solution and in our Software Development Kit since 2016. Thank you :)

### CODE REVIEW

**Comment by adamdruppe** [comment]
Your image files are empty, was that intentional?

**Comment by PELock** [comment]
> Your image files are empty, was that intentional?

Empty? I have used GitHub desktop to create a fork, I put 2 of them inside the fork, let me check that, one was 13kb the other was 16kb.

**Comment by PELock** [comment]
> Your image files are empty, was that intentional?

They are not empty, please check it

https://github.com/PELock/dlang.org/blob/master/images/orgs-using-d/pelock_hq.png
https://github.com/PELock/dlang.org/blob/master/images/orgs-using-d/pelock.png

Thank you

**Comment by adamdruppe** [comment]
oooh I'm sorry, yeah it was my mistake because it didn't show on the "files changed" tab until I clicked the rich view.

**Review by maxhaton — APPROVED** [review]

**Comment by PELock** [comment]
Thank you :)

**Pull request merged**
