### PR TITLE
Add AID to organisations using D.

### PR DESCRIPTION
**Pull request by veelo**

### CODE REVIEW

**Comment by thewilsonator** [comment]
cc @dcarp you fine with this?

**Comment by veelo** [comment]
> cc @dcarp you fine with this?

Yeah this is minimal, there'd be more value if you could supply a quote, for example. I fished the logo off of your company website and cropped off the words, as they scale poorly to the standard width of 200px. They might work if you can supply an SVG formatted logo, if you prefer.

**Comment by dcarp** [comment]
Thanks for this PR! Let me clear the things up and I'll get back to you.

**Comment by dcarp** [comment]
The `https://` prefix, breaks the link. See the AID hiring link here: http://dtest.dlang.io/artifact/website-e610d2f75c1e7c1e96fde68e2735612d34b8980e-fa00857434cc307615dd4b7011846a20/web/orgs-using-d.html

**Comment by veelo** [comment]
> Thanks for this PR! Let me clear the things up and I'll get back to you.

You're welcome! The logo as it is now is rather heavy. If SVG is not available (with the words on the side), it might be good to reduce the size a bit by adding some transparent padding. I'll await your instructions. Feel free to take over this PR if that is easier for you.

**Comment by dcarp** [comment]
@veelo I created a PR for your branch. If you merge that, the changes should also be visible here. That was the way that I found to update the logo image.

**Pull request merged**
