### PR TITLE
Replace company links with their success stories + rename testimonials link to success stories

### PR DESCRIPTION
**Pull request by wilzbach**
CC @JackStouffer

### CODE REVIEW

**Comment by MetaLang** [comment]
Not sure if this is intentional or not:

image

**Comment by wilzbach** [comment]
> Not sure if this is intentional or not:

Well the icon change was intentional. I just quickly browsed the list (http://fontawesome.io/icons/) - maybe someone has a better idea?

**Comment by MetaLang** [comment]
Ah, I see what you were going for. At first glance I thought it was mismatched quotes.

**Comment by JackStouffer** [comment]
`fa-newspaper-o` or the heart would work

**Comment by wilzbach** [comment]
@MetaLang excellent idea - I really like this:

image

(It's on the PR, so everyone can play for with it)

> fa-newspaper-o

That's already used for "News" directly beneath. I used the `heart`.

**Comment by JackStouffer** [comment]
I don't think that's what @MetaLang was talking about; I think he was just suggesting to use the heart symbol. Personally, I believe the quote clutters that space a bit too much.

**Comment by wilzbach** [comment]
>  Personally, I believe the quote clutters that space a bit too much.

We could also remove a couple of line breaks:

image

**Comment by MetaLang** [comment]
@wilzbach Yes, your second example is what I had in mind.

**Comment by wilzbach** [comment]
CC @andralex and @CyberShadow as this is a change to the front page.

**Comment by JackStouffer** [comment]
Nice! One more nitpick, can you change the padding on the org list to `padding: 20px 0;` and the `padding-top` on the testimonial div to `15px`? I think it just gives everything a bit more room to breathe.

**Comment by wilzbach** [comment]
> One more nitpick,

Sure, done.

Before:

image


image



After:

image

image

**Pull request merged**
