### PR TITLE
Added padding to links in Phobos book table

### PR DESCRIPTION
**Pull request by JackStouffer**
Just a small improvement. I think the links can use a little breathing room.

CC @wilzbach

### CODE REVIEW

**Comment by JackStouffer** [comment]
Before

screen shot 2017-03-01 at 10 22 49 am

After

screen shot 2017-03-01 at 10 22 00 am

**Comment by wilzbach** [comment]
Hmm also note that this will modify existing pages like, e.g.

image

After:

image

Given that this page has its issues - it looks a bit weirder afterwards. However on the regex page it looks definitely better, so I am undecided.
@CyberShadow what's your opinion?
How about enabling it only for BOOKTABLES with the `quickindex` class?

A bit OT
-----------

What do you think about using "Match, Build, Replace, Split, Objects" as category names instead?

**Comment by CyberShadow** [comment]
> @CyberShadow what's your opinion?

I guess it is a minor improvement.

Would be nice to avoid `px` units, especially since this is something that is intended to be relative to the font size.

**Comment by JackStouffer** [comment]
> Would be nice to avoid px units, especially since this is something that is intended to be relative to the font size.

I'll change it

> Hmm also note that this will modify existing pages like, e.g.

I will note that that page looks much better on the /phobos/ version

screen shot 2017-03-01 at 10 54 13 am

**Comment by JackStouffer** [comment]
The odd spaces come from these `&nbsp;`s that are inserted everywhere for some reason

**Comment by wilzbach** [comment]
>  The odd spaces come from these `&nbsp;`s that are inserted everywhere for some reason. If you delete them from the HTML, the page looks normal

Alrighty - yet another weirdness of Ddoc. I will have a look at it. Maybe I can find the reason ...

**Comment by wilzbach** [comment]
> The odd spaces come from these &nbsp;s that are inserted everywhere for some reason. 

It's comes from the `SUBREF` macro here:
https://github.com/dlang/phobos/blob/master/std/algorithm/package.d#L175

It seems like a hack to get a better text justification...

**Comment by JackStouffer** [comment]
Styling stuff should live in CSS.

Delete the non-breaking space and see what happens.

**Pull request merged**
