### PR TITLE
Add GSOC 2019 to DLF intro

### PR DESCRIPTION
**Pull request by mdparker**
The intro on the foundation/about page was a little out of date. And it's supposed to be mirrored on the foundation/donate page, too.

### CODE REVIEW

**Comment by thewilsonator** [comment]
I'm glad I'm not the only one who hates that check.

**Comment by mdparker** [comment]
And now DAutoTest has failed. Same error as my other PR:

"../dmd/src/dmd/doc.d(368,34): Error: file `"default_ddoc_theme.ddoc"` cannot be found or not in a path specified with `-J`"

**Comment by mdparker** [comment]
Does anyone have any ideas about the CircleCI failure? I can't see anything in the log that points to an actual thing I can fix.

**Comment by thewilsonator** [comment]
Err, its all green now.

**Comment by mdparker** [comment]
Ah. Well, it was red for me two hours ago. Thanks!

**Pull request merged**
