### PR TITLE
pick changelog fixes from master

### PR DESCRIPTION
**Pull request by MartinNowak**
- did not land in generated changelog as that is generated from stable
  (see https://github.com/dlang/phobos/pull/6199 and https://github.com/dlang/phobos/pull/6226)

### CODE REVIEW

**Comment by MartinNowak** [comment]
We should really figure out how to update the generated changelog additively and purge changelog fragments right away when merging. This would also make the pending changelog accurately.

**Comment by wilzbach** [comment]
Hmm the error seems unrelated, but I'm without computer for today.

**Comment by wilzbach** [comment]
> We should really figure out how to update the generated changelog additively and purge changelog fragments right away when merging. 

Yeah, this is bothering me too. I will have a look into this next week. It should be as easy as reading the full text blob and dumping it again. An alternative would be to allow the script to read files from e.g. `changelog/2.079.0/dmd`

**Comment by MartinNowak** [comment]
> I will have a look into this next week. It should be as easy as reading the full text blob and dumping it again.

Thx that would be great. Let's figure out if we can make it parseable. That would also help with branches and backporting at some point.

It's quite structure at least. Alternatively we could save the combined changelog in some structured format (JSON, XML) and generate a .dd from that, but it doesn't seem too necessary.

```d
Ddoc

$(CHANGELOG_NAV_LAST 2.078.3)

$(VERSION ...
  $(BUGSTITLE_TEXT_HEADER
    $(LI ...)
    $(LI ...)
  )
  $(BUGSTITLE_TEXT_HEADER ...
    $(LI ...)
    $(LI ...)
  )
  $(BUGSTITLE_TEXT_HEADER ...
    $(LI ...)
    $(LI ...)
  )
  $(CHANGELOG_SEP_HEADER_TEXT_NONEMPTY)
  $(CHANGELOG_SEP_HEADER_TEXT)
  $(BUGSTITLE_TEXT_BODY
    $(LI ...)
    $(LI ...)
    $(LI ...)
  )
  $(BUGSTITLE_TEXT_BODY
    $(LI ...)
    $(LI ...)
    $(LI ...)
  )
  $(CHANGELOG_SEP_TEXT_BUGZILLA)
  $(BUGSTITLE_BUGZILLA
    $(LI ...)
    $(LI ...)
    $(LI ...)
  )
  $(BUGSTITLE_BUGZILLA
    $(LI ...)
    $(LI ...)
    $(LI ...)
  )
)
$(D_CONTRIBUTORS_HEADER 78)
$(D_CONTRIBUTORS
  $(D_CONTRIBUTOR ...)
  $(D_CONTRIBUTOR ...)
)
$(D_CONTRIBUTORS_FOOTER)
$(CHANGELOG_NAV_LAST 2.078.3)
Macros:
    VER=2.079.0
    TITLE=Change Log: $(VER)
```

**Comment by MartinNowak** [comment]
CircleCI is using the wrong base branch.
dmd_access failure is present on stable in general http://dtest.dlang.io/results/833dabe8e414cc828288063d4dd274acf586ff1e/!base/build.log.

**Pull request merged**
