### PR TITLE
Use _pending for the latest changelog entries

### PR DESCRIPTION
**Pull request by wilzbach**
Regarding https://github.com/dlang/dlang.org/pull/1814#issuecomment-313988447

A simple solution is to use `_pending` for the automatically generated changelog. (@MartinNowak) doesn't seem to use the Makefile target here anyways.

Regarding the changelog menu: I wasn't really sure how we should handle the case when a prerelease is progress, so I simply renamed them "Nightlies" as this actually is exactly what the page depicts.

CC @CyberShadow

### CODE REVIEW

**Comment by CyberShadow** [comment]
Looks like we had the same idea: https://github.com/dlang/phobos/pull/5504#issuecomment-314165842

**Comment by CyberShadow** [comment]
Thanks!

The _pre page still has nothing on it to indicate it's not yet released, except the future date and URL, sigh.

**Comment by wilzbach** [comment]
Hmm any idea what could have went wrong with the deployment?
The changes were properly shown in DAutoTest, but aren't visible on dlang.org, e.g.

http://dlang.org/changelog/2.075.0_pending.html

**Comment by MartinNowak** [comment]
What was the point of using `2.076.0_pending.html` instead of just `2.076.0.html` having pending somewhere clearly visible on the page?

**Comment by CyberShadow** [comment]
I think because `update_nav.sh` infers the page type from the filename?

**Comment by wilzbach** [comment]
>> What was the point of using 2.076.0_pending.html instead of just 2.076.0.html having pending somewhere clearly visible on the page?
> I think because update_nav.sh infers the page type from the filename?

Yes, and also it's not trivial to know the future release version of `master` as this would require detecting the beta tags and this `_pending` seemed a lot easier.

**Pull request merged**
