### PR TITLE
Cleanup ddmd -> dmd transition

### PR DESCRIPTION
**Pull request by wilzbach**
Can be merged safely if no changes appear on the DAutoTest diff.

### CODE REVIEW

**Comment by andralex** [comment]
is there a chicken-and-egg problem with the testers?

**Comment by wilzbach** [comment]
> is there a chicken-and-egg problem with the testers?

No I forgot that we have to wait until `stable` is officially released, but that should happen fairly soon :)

**Comment by wilzbach** [comment]
With 2.078.0 being released today, this is unblocked :)

**Comment by andralex** [comment]
awesome!

**Pull request merged**
