### PR TITLE
document changes to mangling of type and identifier back refs

### PR DESCRIPTION
**Pull request by rainers**
This documents the changes to the mangling in https://github.com/dlang/dmd/pull/5855

### CODE REVIEW

**Comment by rainers** [comment]
Updated to recent changes to the proposed new mangling.

I've also added some clarification to the existing mangling.

**Comment by rainers** [comment]
Merge conflicts resolved.

This documentation change is still missing for the new mangling.

@klickverbot you've been asking for a more rigorous specification. Any specific issues you can point at? (I've stared too much at this and became blind to the complications).

**Comment by andralex** [comment]
closing and reopening in a hope to kick off the build...

**Comment by andralex** [comment]
nope... @rainers please to a git push?

**Comment by rainers** [comment]
Auto tester seems to fail because trailing white spaces have crept into changelog/2.076.dd with https://github.com/dlang/dlang.org/pull/1880

**Comment by rainers** [comment]
@andralex white space issues fixed in https://github.com/dlang/dlang.org/pull/1882

**Comment by andralex** [comment]
thx folks

**Pull request merged**
