### PR TITLE
Add documentation for Objective-C classes

### PR DESCRIPTION
**Pull request by jacob-carlborg**
This is the spec update for https://github.com/dlang/dmd/pull/9179.

### CODE REVIEW

**Comment by thewilsonator** [comment]
You need to escape all your `,` in `$(P some, text)` with `$(P $(ARGS some, text))` see https://github.com/dlang/dlang.org/pull/2453#discussion_r245378324

**Comment by adamdruppe** [comment]
ddoc is so unbelievably bad. you guys really should ditch it so writers can spend less time on syntax and more time on content. just fyi.

**Comment by jacob-carlborg** [comment]
> You need to escape all your , in $(P some, text) with $(P $(ARGS some, text)) see #2453 (comment)

You're kidding? The existing text doesn't do that.

**Comment by thewilsonator** [comment]
Oh I was dealing with lists, hmm. IDK what the problem is then.

**Comment by thewilsonator** [comment]
>  you guys really should ditch it

Would love to.

**Comment by jacob-carlborg** [comment]
@thewilsonator it's green now. I had an extra comma where there shouldn't be one.

**Pull request merged**
