### PR TITLE
Fixup `scope` attribute documentation

### PR DESCRIPTION
**Pull request by dkorpel**
Fix some mistakes from https://github.com/dlang/dlang.org/pull/3284

I'm still struggling with building locally, so don't merge until I check the rendered output from the CI.

### CODE REVIEW

**Review by maxhaton — APPROVED** [review]

**Comment by dkorpel** [comment]
It's still adding empty paragraphs after lists / code blocks sometimes

**Comment by aG0aep6G** [comment]
> It's still adding empty paragraphs after lists / code blocks sometimes

Lists (`<ul>`) and code blocks (`<pre>`) are block elements just like paragraphs (`<p>`). You can't put other blocks inside a `<p>`. Make sure you're closing the `$(P ...)` before starting another block.

**Comment by aG0aep6G** [comment]
> Make sure you're closing the `$(P ...)` before starting another block.

I.e., this is wrong:

```
$(P
    text
    $(UL ...)
    more text
    ---
    code
    ---
)
```

You need to do this:

```
$(P text)
$(UL ...)
$(P more text)
---
code
---
```

**Comment by dkorpel** [comment]
> Make sure you're closing the `$(P ...)` before starting another block.

Thanks!

**Pull request merged**
