### PR TITLE
Add Flipcause to the donate page.

### PR DESCRIPTION
**Pull request by mdparker**
We've signed up with Flipcause to create and manage targeted donation campaigns. The general fund campaign is permanent and ongoing, and needs to be on the donate page.

### CODE REVIEW

**Comment by mdparker** [comment]
We're on a free trial and the clock is ticking. The sooner I can get this merged and make an announcement about it, the better.

**Comment by jacob-carlborg** [comment]
The build is failing.

**Comment by wilzbach** [comment]
They have quite an overhead:

image

**Comment by wilzbach** [comment]
Build failure:

```
Searching for trailing whitespace
./foundation/donate.dd:36:    donations and provide more value to donors. Donating through Flipcause can enable us 
```

**Pull request merged**
