### PR TITLE
Add D-Man looking at other languages to interface with C,C++,ObjC

### PR DESCRIPTION
**Pull request by wilzbach**
Found another lovely D-Man. Author is again [meiz_sandwich](https://twitter.com/meiz_sandwich)
- I added it to C,C++,ObjC - probably one or two is enough
- We could add their custom language symbol at which the D-Man is looking at

image

### CODE REVIEW

**Comment by CyberShadow** [comment]
This seems a little forced.

**Comment by majiang** [comment]
IMO this picture, D-man with an arrow, is more suitable for Vector Extensions page.

**Comment by wilzbach** [comment]
> IMO this picture, D-man with an arrow, is more suitable for Vector Extensions page.

good idea, @WalterBright what do you think?

**Comment by wilzbach** [comment]
> IMO this picture, D-man with an arrow, is more suitable for Vector Extensions page.

ping @WalterBright for feedback

**Comment by AndrejMitrovic** [comment]
It would be cool if there was one holding hands with C, like they're friends.

**Comment by wilzbach** [comment]
> It would be cool if there was one holding hands with C, like they're friends.

@AndrejMitrovic to clarify: I am an horrible artist and all these drawings come from meiz_sandwich. I merely pushed his lovely [drawings](https://github.com/wilzbach/d-mans) to the general public ;-)

So unfortunately I can't produce new drawings and we have to decide between using it for one of the proposed pages (e.g. Vector extensions)  or closing this proposal.

**Comment by wilzbach** [comment]
Closing this as I lost interest in pushing this. In case someone wants to pursue this, I started a repo with D-mans collected from all over the world: https://github.com/wilzbach/d-mans

**Pull request closed without merging**
