### PR TITLE
Visual improvements to orgs using D

### PR DESCRIPTION
**Pull request by wilzbach**
- dont hyphenate the uses
- removed duplicate "hiring"

### CODE REVIEW

**Comment by CyberShadow** [comment]
Can we change the text at the bottom?

"Is your organization missing from this page? Please [create an issue](#) or [open a pull request](#)."

Also, what order are the companies in? E.g. Rust goes with alphabetical.

**Comment by CyberShadow** [comment]
> ```
    - max. dims: 200x100 (resize with e.g. `mogrify -resize 200x100 image.png`)
```

Why? On high-DPI screens (mobile devices) the extra resolution will not go to waste.

Most logos are simple shapes which do not suffer in file size much at bigger resolutions.

**Comment by CyberShadow** [comment]
> ```
    - if you need commas, use `$(COMMA)`
```

Is this still needed after the move to `$0`?

**Comment by wilzbach** [comment]
> Can we change the text at the bottom?

Sure. Thanks & done

> Also, what order are the companies in? E.g. Rust goes with alphabetical.

Initially it was based on where I had content with similar height, but yes sorting alphabetically is fair to all. I will submit another PR ;-)

> Why? On high-DPI screens (mobile devices) the extra resolution will not go to waste.

It sounded like a reasonable cut-off for me, but we can of course change that.
- Currently the same images are used for the front page too.
- the "real" size is 150x75 at the moment

> if you need commas, use `$(COMMA)`

Yes, we use `$0` only for the FA_QUOTES.

**Comment by CyberShadow** [comment]
Yep, there should not be restrictions on logo size. In any case we should have the original in the repo, and maybe a scaled down version if necessary (see the OS logos for the download page).

In addition to benefiting high-DPI displays, a future site redesign might require logos of different resolution.

**Comment by wilzbach** [comment]
> Yep, there should not be restrictions on logo size. In any case we should have the original in the repo, and maybe a scaled down version if necessary 

Okay I added a better explanation.

> (see the OS logos for the download page).

Aren't they also all less than `50x50` at the moment?

**Comment by CyberShadow** [comment]
> Aren't they also all less than 50x50 at the moment?

Ah yes, the higher res ones + conversion commands are in the git history.

**Pull request merged**
