### PR TITLE
Allow `ref` and `auto ref` in `IfCondition` declarations

### PR DESCRIPTION
**Pull request by Bolpat**
As [DIP 1046](https://github.com/dlang/DIPs/blob/master/DIPs/accepted/DIP1046.md) *(`ref` For Variable Declarations)* has been accepted, probably, `ref` (and `auto ref`) should be allowed for the condition in `if`, `while`, and `switch` statements:

```d
int** pptr = …;
if (ref int* ptr = *pptr) …;
```
Of course, the condition tests whether the variable (`ptr` in the example) is `true`-like, not whether the reference is a non-null reference. In the example, it tests `ptr !is null`, and **not** `&ptr !is null` (or, equivalently, `pptr !is null`).

```d
if (auto ref x = mystery()) …;
```
Especially in template contexts, `auto ref` could be used to make `x` be a `ref` if `mystery()` returns by reference, but a value otherwise.

### CODE REVIEW

**Comment by dkorpel** [comment]
This doesn't account for combinations, these also parse currently:

```D
if (scope ref x = b)
if (const ref x = b)
if (scope const ref x = b)
if (auto scope ref const x = b)
```

**Comment by Bolpat** [comment]
I didn’t know `auto` and `ref` allowed other tokens between them. But apparently, they do.

**Comment by Bolpat** [comment]
@dkorpel, it it fine? Merge?

**Comment by dkorpel** [comment]
The current formulation doesn't allow `if (const ref x = y)`

**Review by dkorpel — APPROVED** [review]
I misread it

**Comment by Bolpat** [comment]
> I misread it

No issue. I misread a lot, actually.

**Comment by ntrel** [comment]
I don't think `if (ref x = y)` actually compiles yet. https://github.com/dlang/dmd/pull/16428 is not merged, and I don't know if it covers that case.

**Comment by Bolpat** [comment]
> I don't think `if (ref x = y)` actually compiles yet. [dlang/dmd#16428](https://github.com/dlang/dmd/pull/16428) is not merged, and I don't know if it covers that case.

The spec technically isn’t supposed to document DMD’s behavior, but what DMD’s behavior ought to be. And it ought to be because the respective DIP was accepted.

**Comment by ntrel** [comment]
@Bolpat I think it's confusing. There should at least be a note that the reference compiler doesn't implement it.

> it ought to be because the respective DIP was accepted.

The DIP didn't mention `if (ref`?

**Comment by Bolpat** [comment]
> The DIP didn't mention `if (ref`?

The DIP is written rather incomplete. It’s of course intended.

I just tried out and `if (ref` works. `if (auto ref` does not work, but probably ought to.

**Comment by ntrel** [comment]
Ok, thanks. The dmd pull is merged now anyway.

**Pull request merged**
