### PR TITLE
Revert "Add SAoC banner"

### PR DESCRIPTION
**Pull request by wilzbach**
Reverts dlang/dlang.org#2428

To be merged around 15th of August. Possibly a few days earlier as one needs time to prepare a successful application.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Why is this being reverted?

**Comment by wilzbach** [comment]
It's the easiest way to remove it once application period is over?

**Comment by jacob-carlborg** [comment]
Ah, sorry, I didn't see that it shouldn't be merged until 15th of August.

**Comment by wilzbach** [comment]
As the deadline will expire in a few hours, I think we can merge this now.

**Comment by wilzbach** [comment]
Also added a revert of the right box text announcement (https://github.com/dlang/dlang.org/pull/2426)

**Comment by wilzbach** [comment]
Using my admin permissions now as the deadline has passed on almost all timezones now and it's a trivial revert.

**Pull request merged**
