### PR TITLE
added arabiaweather to orgs-using-d

### PR DESCRIPTION
**Pull request by AlQurashi**

### CODE REVIEW

**Comment by CyberShadow** [comment]
Thanks! Do you think there is link to a blog post, GitHub account, or hiring page which would be appropriate to add?

**Comment by AlQurashi** [comment]
Neither the GitHub account nor the careers page is appropriate to add, we have a TechTalk for one of our members about D in Arabic linked [here](https://www.youtube.com/watch?v=egKU2xOlgbw), shall we add it?

**Comment by CyberShadow** [comment]
I think a link to the talk would work fine, just mention that it's in Arabic in parens. It would have been nicer if it had subtitles (even auto-generated would work, and those could be translated automatically to other languages), but it doesn't look like YouTube auto-generates subtitles for Arabic yet.

**Comment by AlQurashi** [comment]
Just pushed, we'll be considering English sublitles.

**Pull request merged**
