### PR TITLE
Merge remote-tracking branch 'upstream/stable' into merge_stable

### PR DESCRIPTION
**Pull request by MartinNowak**
Conflicts:
	changelog/changelog.ddoc
	posix.mak

### CODE REVIEW

**Comment by MartinNowak** [comment]
I didn't run any preprocessor and update_nav.sh was still there, so I didn't notice @wilzbach.
https://gist.github.com/MartinNowak/a471fe7ddbfeef205cdf04c93a94c6d0#file-release-sh-L77
I've seen the change though, but also I don't think it was on stable.

**Comment by MartinNowak** [comment]
For reference https://github.com/dlang/dlang.org/pull/2159.

**Comment by MartinNowak** [comment]
Seems like I still need to call update_nav to update the navigation ;).

**Comment by wilzbach** [comment]
> I've seen the change though, but also I don't think it was on stable.

Yeah, sorry. I was commenting from my phone and there's it always hard to search for PRs with their bulky mobile UI.

> Seems like I still need to call update_nav to update the navigation ;).

Ah sorry. Yeah, maybe I can make it obsolete for the next release ;-)

**Pull request merged**
