### PR TITLE
Remove unused articles

### PR DESCRIPTION
**Pull request by wilzbach**
I'm just checked whether this is really unused.
If so, we might want to move the content to the wiki, s.t. it's not entirely lost.

### CODE REVIEW

**Comment by JackStouffer** [comment]
Or adapt them to blog posts. CC @mdparker

**Comment by mdparker** [comment]
Blog posts would be nice, depending on the content.

**Comment by JinShil** [comment]
I believe these articles came from:
https://digitalmars.com/d/2.0/cppstrings.html
https://digitalmars.com/d/2.0/cpp0x.html

**Comment by wilzbach** [comment]
> Blog posts would be nice, depending on the content.

Well it's an old comparison between D and C++0x.
There's not so much we can revive - especially given the newer https://dlang.org/articles/cpptod.html exists

**Pull request merged**
