### PR TITLE
Insert newlines for readability in html generation

### PR DESCRIPTION
**Pull request by andralex**
Supersedes https://github.com/dlang/dlang.org/pull/1806. Follow-up for https://github.com/dlang/dmd/pull/6972,

### CODE REVIEW

**Comment by CyberShadow** [comment]
```diff

-<div class="val"><p class="keyval Section"><span class="key keySection">Source:</span>
+
+<div class="val"><p class="keyval Section"><span class="key keySection">Source::</span>
+
```
There's now a double colon.

**Comment by CyberShadow** [comment]
Same with other sections "Input::", "TODO::"

**Comment by andralex** [comment]
@CyberShadow Yes, needs https://github.com/dlang/dmd/pull/6972 to get everything in place.

**Comment by CyberShadow** [comment]
Oops, I thought that was already merged.

**Comment by andralex** [comment]
@CyberShadow lgty?

**Comment by CyberShadow** [comment]
@andralex  The double-colons are still there. And I don't think it's just the result before the DMD PR was merged. (I should really add a build date field to DAutoTest's web UI...)

**Comment by andralex** [comment]
@CyberShadow looks correct on my machine, pushed again perhaps it'll restart generation.

**Comment by CyberShadow** [comment]
Still there. Look at web/phobos-prerelease/ddmd_backend_bcomplex.html

**Comment by andralex** [comment]
OK, let's see now...

**Pull request merged**
