### PR TITLE
Rename ddoc.d -> ddoc_preprocessor.d

### PR DESCRIPTION
**Pull request by wilzbach**
@ZombineDev pointed out that `ddoc.d` is a rather uninformative name.

### CODE REVIEW

**Comment by andralex** [comment]
I find this more confusing than before. 

* Before: "ddoc.d -> aha, that is the file doing the ddoc stuff"
* After: "ddoc_preprocessor.d -> wait, is there some postprocessing or some other ddoc work as well that I need to worry about?"

Restructuring should add net value, this is at the very best a lateral step.

**Comment by wilzbach** [comment]
FYI: I opened this PR, s.t. https://github.com/dlang/dlang.org/pull/2072 doesn't get blocked.

For a bit of history:
- https://github.com/dlang/dlang.org/pull/2060 (automatic TOC generation with `ddoc.d` - merged - PR that introduced `ddoc.d`)
- https://github.com/dlang/dlang.org/pull/2069 (moves the assert -> writeln step into `ddoc.d` - blocked)

**Comment by andralex** [comment]
So it seems we added automation that requires us to rename modules in our code. Seems the right place to change things is in the automation, no?

**Comment by wilzbach** [comment]
> So it seems we added automation that requires us to rename modules in our code.

I'm not sure I can follow. To what "automation" are you referring to? Do you mean the assert->writeln transformation?
I added the rewriting of [`assert`'s in the runnable examples](https://dlang.org/blog/2017/03/08/editable-and-runnable-doc-examples-on-dlang-org) last year. However, it was always pretty ugly because (1) it requires making a full copy of the Phobos repository and (2) it requires the Phobos repository to be checked-out and thus always does the existence check (even on `make clean`). That's why @CyberShadow is so happy that removing that extra step in #2069, but I'm not sure how that's related to this PR which is just about renaming the tool.

I don't care how the Ddoc wrapper tool is named as long as the name bike-shedding doesn't block my PRs. Hence, I moved this in a separate PR.
(I picked `ddoc.d` myself, so I obviously liked it.)

**Comment by CyberShadow** [comment]
> (I picked ddoc.d myself, so I obviously liked it.)

I liked `ddoc` too. But it really doesn't matter, at all.

**Pull request merged**
