### PR TITLE
Upgraded to jQuery 3.2.1

### PR DESCRIPTION
**Pull request by JackStouffer**
Google's auditing tool in chrome notified me that jquery 1.7.2 has two known XSS vulns and this marked the page down (it probably marks down our Page Rank as well). I've upgraded us to the latest and greatest. I did a cursory check of our existing JS code to see if anything was broken. I didn't see anything, and we weren't doing anything complicated with jQuery anyway.

Moved to jQuery's recommended CDN which supports integrity checks.

### CODE REVIEW

**Comment by JackStouffer** [comment]
jQuery vulnerabilities: https://snyk.io/vuln/npm:jquery#lh@1.7.2

**Comment by quickfur** [comment]
+1, we definitely need to get this in.  Security vulnerabilities are Not Good, both in the sense of security, and also from a marketing / PR perspective.

**Comment by CyberShadow** [comment]
We're *probably* not affected but it's still an obviously good idea to update.

However, this updates across *two* major versions, which IIRC have breaking changes. We should either test thoroughly that all dynamic content on the site still works, or just elect to update to the latest minor version (1.12.14, it seems).

**Comment by CyberShadow** [comment]
You need to update posix.mak BTW.

**Comment by JackStouffer** [comment]
btw @wilzbach the certificate for https://contribs.dlang.io seems to be out of date.

**Comment by JackStouffer** [comment]
Closing. No longer interested

**Pull request closed without merging**
