### PR TITLE
Use Smaller Netflix Image on Orgs Using D Page

### PR DESCRIPTION
**Pull request by JackStouffer**
Saves a couple of KBs

### CODE REVIEW

**Comment by CyberShadow** [comment]
Not sure if this is making it more or less consistent... besides, it's a household brand, nothing wrong with it standing out a bit.

**Comment by JackStouffer** [comment]
@CyberShadow Not sure what you're referring to. All this PR does is change the Netflix image from the  800px wide version to the 400px wide version because its only ever displayed at a 178px width.

**Comment by CyberShadow** [comment]
There is a visible difference in DAutoTest's HTML preview. Was that not intended, then?

**Comment by CyberShadow** [comment]
> All this PR does is change the Netflix image from the 800px wide version to the 400px wide version because its only ever displayed at a 178px width.

Only on regular DPI displays... mobile devices and high-DPI displays benefit from the extra pixels. Ideally we'd be using SVGs or imgsets here.

**Comment by JackStouffer** [comment]
>Only on regular DPI displays... mobile devices and high-DPI displays benefit from the extra pixels. Ideally we'd be using SVGs or imgsets here.

Ah, ok. When I have time I'll look into getting an SVG

**Pull request closed without merging**
