### PR TITLE
Provide infos how to add an org using d

### PR DESCRIPTION
**Pull request by wilzbach**
Inspired by @llaine and #1381, I thought it's worth adding easily accessible information for future org additions.

### CODE REVIEW

**Comment by CyberShadow** [comment]
Why are we putting documentation for *one single page* into the file documenting the entire project? Are we going to start adding documentation on how to update each dlang.org page here next?

**Comment by wilzbach** [comment]
> Why are we putting documentation for one single page into the file documenting the entire project? Are we going to start adding documentation on how to update each dlang.org page here next?

Fair enough - I added a couple of spaces and moved it before the title, s.t. it hopefully doesn't get ignored the next time. Should I remove the README too?

**Comment by CyberShadow** [comment]
Yes.

You're taking the wrong approach to this problem.

What part of the text are potential contributors most likely to immediately start editing?

The end of the list of organizations.

That's where you need to add the explanatory text. So, either put the instructions there, or add a comment pointing them towards the instructions at the top of the file.

**Comment by wilzbach** [comment]
> You're taking the wrong approach to this problem.
>
> What part of the text are potential contributors most likely to immediately start editing?
>
> The end of the list of organizations.
> That's where you need to add the explanatory text. So, either put the instructions there, or add a comment pointing them towards the instructions at the top of the file.

Alrighty - I put a pointer in there ;-)

**Pull request merged**
