### PR TITLE
Change download button text to be less confusing.

### PR DESCRIPTION
**Pull request by mdparker**

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Please squash commits.

**Comment by mdparker** [comment]
Doesn't that happen automatically?

**Comment by jacob-carlborg** [comment]
No.

**Comment by mdparker** [comment]
I made the edits online and will be away fom my computers for a while. So is the 'Squash & Merge' button a config option?

**Comment by ZombineDev** [comment]
> So is the 'Squash & Merge' button a config option?

Yep, I just squashed your commits with the help of it ;)

**Pull request merged**
