### PR TITLE
Add conversions of base class to derived class (arrays)

### PR DESCRIPTION
**Pull request by nordlow**
Spec update of https://github.com/dlang/dmd/pull/11610/.

### CODE REVIEW

**Comment by nordlow** [comment]
This is my first change of dlang.org. Can somebody explain the source of the errors?

**Comment by nordlow** [comment]
I guess the last example won't run until https://github.com/dlang/dmd/pull/11610/ is merged.

**Comment by nordlow** [comment]
Ping. Ready to go?

**Comment by thewilsonator** [comment]
DAutoTest failed
```
---
void main() {
import std.stdio;
class Base {}
class Derived : Base {}
unittest
{
    Base bd = new Derived();              // implicit conversion
    Derived db = cast(Derived)new Base(); // explicit conversion
}

}
---
__stdin.d(5): Error: found `unittest` instead of statement
__stdin.d(11): Error: unrecognized declaration
```

Not sure why you can't have unittests local to a function.

**Comment by nordlow** [comment]
> DAutoTest failed
> 
> ```
> ---
> void main() {
> import std.stdio;
> class Base {}
> class Derived : Base {}
> unittest
> {
>     Base bd = new Derived();              // implicit conversion
>     Derived db = cast(Derived)new Base(); // explicit conversion
> }
> 
> }
> ---
> __stdin.d(5): Error: found `unittest` instead of statement
> __stdin.d(11): Error: unrecognized declaration
> ```
> 
> Not sure why you can't have unittests local to a function.

So I guess I should make the normal functions becoming local to `main` then?

**Comment by thewilsonator** [comment]
I think so.

**Comment by thewilsonator** [comment]
Oh wait. I think the whole thing gets wrapped in a main function by the spec example processor. There are no asserts there anyway its probably just easier to remove the unittest and leave the code inside the unittest.

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Anyway ping me when its green.

**Comment by nordlow** [comment]
Done. Let's see if things go green now.

**Comment by nordlow** [comment]
Thanks

**Pull request merged**
