### PR TITLE
remove wrong `P` around `LI`s

### PR DESCRIPTION
**Pull request by aG0aep6G**

### CODE REVIEW

**Comment by wilzbach** [comment]
Shouldn't in theory there be a `UL` around the `LI`s?
I guess we are lucky that HTML5 is so error-tolerant (this change doesn't change the visual output)

Btw I am really looking forward to the 2.072 branch-off, s.t. we can introduce more automation to this error-prone process.

**Comment by aG0aep6G** [comment]
> Shouldn't in theory there be a UL around the LIs?

`BUGSTITLE` puts the `LI`s into an `OL` ([in changelog.ddoc](https://github.com/dlang/dlang.org/blob/8a7ffb28d2e96759efad8bd8dddfc8fbfc6e3e42/changelog/changelog.ddoc#L35)).

**Comment by wilzbach** [comment]
> BUGSTITLE puts the LIs into an OL (in changelog.ddoc).

Oh sorry, LGTM then ;-)

**Comment by AndrejMitrovic** [comment]
Wasn't this autogenerated with changed.d? So maybe the script needs to be fixed if using that macro is wrong.

**Comment by aG0aep6G** [comment]
> Wasn't this autogenerated with changed.d? So maybe the script needs to be fixed if using that macro is wrong.

Indeed.-> https://github.com/dlang/tools/pull/199

**Comment by MartinNowak** [comment]
Please stop manually editing those files and fix the tool instead.

**Comment by MartinNowak** [comment]
Also there are plenty of existing changelogs w/ those <p> tags, so either fix all or none of them.

**Comment by andralex** [comment]
tool got fixed

**Comment by aG0aep6G** [comment]
> either fix all or none of them.

Fixing all of them: https://github.com/dlang/dlang.org/pull/1479

**Pull request merged**
