### PR TITLE
Improve pragma grammar and links

### PR DESCRIPTION
**Pull request by WalterBright**
Moved the grammar for pragmas to all be in pragma.dd.

Clarified some of the prose.

### CODE REVIEW

**Comment by WalterBright** [comment]
DAutoTest gives no clue in the log what went wrong.

**Comment by PetarKirov** [comment]
@CyberShadow I this this error is something on DAutoTest's side:

```
Getting URL https://api.github.com/repos/dlang/dlang.org/pulls/1021
[2021-02-08 21:13:19.832375] dautotest:  > Cache miss; ratelimit: 4982/5000
[2021-02-08 21:13:19.833570] dautotest: Headers([NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("ETag"):[Header("ETag", "W/\"30d6115cccca0f204f578adb20cfcdbe6fb6674f4c558cc183df75a74381cb7e\"")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("X-GitHub-Media-Type"):[Header("X-GitHub-Media-Type", "github.v3; format=json")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("X-XSS-Protection"):[Header("X-XSS-Protection", "1; mode=block")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("Access-Control-Expose-Headers"):[Header("Access-Control-Expose-Headers", "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("x-ratelimit-used"):[Header("x-ratelimit-used", "18")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("Server"):[Header("Server", "GitHub.com")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("X-RateLimit-Remaining"):[Header("X-RateLimit-Remaining", "4982")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("Transfer-Encoding"):[Header("Transfer-Encoding", "chunked")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("Referrer-Policy"):[Header("Referrer-Policy", "origin-when-cross-origin, strict-origin-when-cross-origin")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("X-RateLimit-Reset"):[Header("X-RateLimit-Reset", "1612820793")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("X-OAuth-Scopes"):[Header("X-OAuth-Scopes", "public_repo, repo:status")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("X-Frame-Options"):[Header("X-Frame-Options", "deny")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("Content-Security-Policy"):[Header("Content-Security-Policy", "default-src 'none'")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("last-modified"):[Header("last-modified", "Tue, 19 Jan 2021 17:20:28 GMT")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("Cache-Control"):[Header("Cache-Control", "private, max-age=60, s-maxage=60")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("X-RateLimit-Limit"):[Header("X-RateLimit-Limit", "5000")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("Vary"):[Header("Vary", "Accept, Authorization, Cookie, X-GitHub-OTP"), Header("Vary", "Accept-Encoding, Accept, X-Requested-With")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("Content-Encoding"):[Header("Content-Encoding", "gzip")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("X-Content-Type-Options"):[Header("X-Content-Type-Options", "nosniff")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("Strict-Transport-Security"):[Header("Strict-Transport-Security", "max-age=31536000; includeSubdomains; preload")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("Content-Type"):[Header("Content-Type", "application/json; charset=utf-8")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("connection"):[Header("connection", "close")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("Date"):[Header("Date", "Mon, 08 Feb 2021 21:13:19 GMT")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("X-GitHub-Request-Id"):[Header("X-GitHub-Request-Id", "D0C2:15F9:52B74B:5B7A92:6021A96F")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("Access-Control-Allow-Origin"):[Header("Access-Control-Allow-Origin", "*")], NormalizedArray!(immutable(char), (s) => s.byCodeUnit.map!(std.ascii.toLower))("X-Accepted-OAuth-Scopes"):[Header("X-Accepted-OAuth-Scopes", "")]])
[2021-02-08 21:13:19.833723] dautotest: Error: Invalid Gzip signature
[2021-02-08 21:13:19.834059] dautotest: Setting status for dlang.org pull 2939 (commit 56b381e97126b0e4afd332c30c16a6757f6c3073) to error (Invalid Gzip signature): http://dtest.dlang.io/results/7d33fc4706be2f3e0cea1b422df15d34acc8ec98/56b381e97126b0e4afd332c30c16a6757f6c3073/
```

**Comment by PetarKirov** [comment]
@WalterBright before the latest DAutoTest failure, the error was that `$(pragma)` was considered a DDoc macro.

**Comment by maxhaton** [comment]
https://www.githubstatus.com/incidents/th4mgzt9y25t there was this?

**Comment by PetarKirov** [comment]
@maxhaton it's quite possible. Let's see...

**Comment by PetarKirov** [comment]
@WalterBright the last build fails with the following error (it is visible if you scroll to the bottom of DAutoTest's build output):

```
Checking DDoc's output
.generated/stable_dmd-2.088.0/dmd2/linux/bin64/rdmd --compiler=.generated/stable_dmd-2.088.0/dmd2/linux/bin64/dmd -conf=.generated/stable_dmd-2.088.0/dmd2/linux/bin64/dmd.conf -main -unittest tools/check_ddoc.d
.generated/stable_dmd-2.088.0/dmd2/linux/bin64/rdmd --compiler=.generated/stable_dmd-2.088.0/dmd2/linux/bin64/dmd -conf=.generated/stable_dmd-2.088.0/dmd2/linux/bin64/dmd.conf tools/check_ddoc.d $(find /dev/shm/dtest/work/repo/dlang.org/web -type f -name "*.html" -not -path "/dev/shm/dtest/work/repo/dlang.org/web/phobos/*")
/dev/shm/dtest/work/repo/dlang.org/web/spec/pragma.html:169: [UNDEFINED MACRO]     <a href="#Pragma"><i>Pragma</i></a> <!--UNDEFINED MACRO: "PSSEMI"-->
1 error found. Exiting.
posix.mak:807: recipe for target 'test' failed
make: *** [test] Error 1
Test failed: object.Exception@ae/sys/d/manager.d(877): Command ["timeout", "1800", "make", "-f", "posix.mak", "DIFFABLE=1", "test"] failed with status 2
```

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
