### PR TITLE
Remove special casing for `objc.d` from the Posix makefile

### PR DESCRIPTION
**Pull request by jacob-carlborg**
This file is now shared for all platforms after the Objective-C integration refactoring: https://github.com/dlang/dmd/pull/6679.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
@ibuclaw @WalterBright This is required for the DAutoTest to pass for https://github.com/dlang/dmd/pull/6679.

I guess this will fail until https://github.com/dlang/dmd/pull/6679 is merged.

**Comment by ibuclaw** [comment]
Looks fine. FYI @CyberShadow.

**Comment by jacob-carlborg** [comment]
> I guess the same will need to be done for objc_glue too if you plan on changing that too?

Yes, one step at the time 😃. I'll wait until I have the PR for the compiler ready.

**Comment by CyberShadow** [comment]
LGTM, but I'm not going to merge this because it looks like by itself it would break master. I understand that merging this simultaneously with https://github.com/dlang/dmd/pull/6679 would fix things again, so whoever merges https://github.com/dlang/dmd/pull/6679 should merge this immediately after.

Even better would be to do this in three steps to avoid breaking master at all. E.g. in the dlang.org makefile, detect whether `objc.d` should be ignored (i.e. whether https://github.com/dlang/dmd/pull/6679 is merged). That would completely avoid the risk of breaking master should merging both PRs somehow still result in tests failing.

**Comment by jacob-carlborg** [comment]
@CyberShadow auto merging has been enabled for the other PR https://github.com/dlang/dmd/pull/6679, can this be merged now? Looks like Iain doesn't have permission to merge this.

**Comment by jacob-carlborg** [comment]
@CyberShadow https://github.com/dlang/dmd/pull/6679 has been merged. This can now be merged as well.

**Comment by jacob-carlborg** [comment]
Thanks.

**Comment by CyberShadow** [comment]
Thanks for handling this @schuetzm, just got back home :)

**Pull request merged**
