### PR TITLE
Improve runnable: disable assert to writeln transformation + make output a pre element

### PR DESCRIPTION
**Pull request by wilzbach**
As of http://forum.dlang.org/post/enjjesmilghothyjlfid@forum.dlang.org

1) the Regex doesn't seem to handle all cases of `assert` -> removed
2) `textarea` shouldn't be used for a readonly output -> `pre`
3) For consistency I also moved the separated CSS up into its group

### CODE REVIEW

**Comment by JackStouffer** [comment]
I'm getting "temporarily unavailable" errors when I try to test this.

**Comment by wilzbach** [comment]
> I'm getting "temporarily unavailable" errors when I try to test this.

Yeah @nazriel doesn't allow CORS requests from the DAutoTest domain (dtest.dlang.io). I have written to him about this for a couple of times already since the last six months. Unfortunately as you have realized with no effect.

**Comment by wilzbach** [comment]
For reference:
@JackStouffer If you open your console you should see something like:

> XMLHttpRequest cannot load https://dpaste.dzfl.pl/request/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://dtest.dlang.io' is therefore not allowed access.

**Comment by wilzbach** [comment]
Ping @CyberShadow or @andralex for merging this fix, s.t. we can post an announcement to reddit ;-)

**Comment by andralex** [comment]
Cool. Not a fan of the rewrite assert->writeln in the first place...

**Comment by CyberShadow** [comment]
Thx. If possible, it would be nice to put all information describing a change in the commit message itself, e.g. what the assert rewrite was (I had no idea) and the justification for the HTML change.

**Pull request merged**
