### PR TITLE
Hashmap: add example for iteration and tuple counting

### PR DESCRIPTION
**Pull request by wilzbach**
This is a modified version of my favorite DLang example for Associative Arrays because:

- shows iteration through arrays and associative arrays
- uses tuples (!)
- has real world use cases (e.g. DNA sequencing)
- it's very concise and "beautiful" (-> easy to understand)

Hence I think it could be worthwhile to list this as an example to the reader.

(Follow-up to https://github.com/dlang/dlang.org/pull/1573)

### CODE REVIEW

**Comment by wilzbach** [comment]
> Doesn't this do UTF decoding? (Yes, it does, you even have `dchar` in there explicitly. Best not to encourage writing code that way?)

Yeah, I wasn't sure about the "best practice".
The [other example](https://dlang.org/spec/hash-map.html#aa_example) assumes the input to be ASCII only and states:

> In general case we should use dchar c for iteration

**Comment by wilzbach** [comment]
> The reason why I think string (decoding) is not appropriate here is that DNA base sequences are not UTF text, but rather byte sequences from the alphabet 

Fair enough - I just wanted to keep the example as simple as possible, but you have made a good case. I updated the example to use `byCodeUnit` instead ;-)

**Comment by CyberShadow** [comment]
TBH, this is nice, but if I were to see this code in the wild I'd just wonder why bother with tuples and ranges if you can use simple dull arrays and achieve the same thing with less code and better performance:
```
        import std.stdio : writefln;

        int[char[2]] aa;

        // The string `arr` has a limited alphabet: {A, C, G, T}
        // Thus, for better performance, iteration can be done _without_ decoding
        auto arr = "AGATAGA";

        // iterate over all pairs in the string and observe each pair
        // ('A', 'G'), ('G', 'A'), ('A', 'T'), ...
        foreach (i; 0..arr.length-1)
            aa[arr[i..$][0..2]]++;

        // iterate over all key/value pairs of the Associative Array
        foreach (key, value; aa)
            writefln("key: %s, value: %d", key, value);
```

So, not sure about this example's illustrative powers. D arrays are awesome too!

**Comment by wilzbach** [comment]
> So, not sure about this example's illustrative powers. D arrays are awesome too!

This now uses this example & rebased to master.

**Comment by CyberShadow** [comment]
I don't remember what the original version looked like any more, but LGTM!

**Pull request merged**
