### PR TITLE
chore(spec/garbage): lookups on associative arrays doesn't use GC

### PR DESCRIPTION
**Pull request by ljmf00**
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Review by Geod24 — APPROVED** [review]

**Comment by Geod24** [comment]
> [1m/dev/shm/dtest/work/repo/dmd/compiler/src/dmd/dtemplate.d(3023): [1;31mError: [mfound `[0;36m$[m` instead of statement

Hum what ?

**Review by ntrel — CHANGES_REQUESTED** [review]
This PR is wrong, lookups can throw which allocates an exception:
```d
auto aa = [1:2];
@nogc void main()
{
	int i = aa[2];
}
```
```
nogcaa.d(4): Error: indexing an associative array in `@nogc` function `D main` may cause a GC allocation
```
The wording needs to be reinstated and changed to "failed lookup".

**Comment by ljmf00** [comment]
> This PR is wrong, lookups can throw which allocates an exception:
> 
> ```d
> auto aa = [1:2];
> @nogc void main()
> {
> 	int i = aa[2];
> }
> ```
> 
> ```
> nogcaa.d(4): Error: indexing an associative array in `@nogc` function `D main` may cause a GC allocation
> ```
> 
> The wording needs to be reinstated and changed to "failed lookup".

See https://github.com/dlang/dmd/pull/14585.

**Comment by ljmf00-wekaio** [comment]
> This PR is wrong, lookups can throw which allocates an exception:

Also to clarify, it is not an `Exception` but rather an `Error`. Errors are thrown using a pre-allocated thread-local storage instance.

**Comment by RazvanN7** [comment]
Even if an error would have been allocated with the GC, since errors should not be captured and are considered exceptional cases, I think that, generally, throwing errors should be @nogc.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
