### PR TITLE
Remove sociomantic from "orgs using D"

### PR DESCRIPTION
**Pull request by Marenz**
It no longer exists and the company that bought it no longer works in D.

### CODE REVIEW

**Comment by ibuclaw** [comment]
Sorry, but who gave you the right to do this @Marenz ?

**Comment by wilzbach** [comment]
I think this was a follow-up to this discussion: https://forum.dlang.org/post/gvcpacymukrgdqdrxwmr@forum.dlang.org

**Comment by ibuclaw** [comment]
> I think this was a follow-up to this discussion: https://forum.dlang.org/post/gvcpacymukrgdqdrxwmr@forum.dlang.org

The request must still come from someone who is employed by or representing DH/Sociomantic, as it is the decision of the company's PR to remove themselves from the list.

That and D is still running in production...

**Comment by Marenz** [comment]
@ibuclaw I wasn't aware I needed permission. I just heard that it was no longer used and figured I update the information. Besides "Sociomantic" as that name does indeed no longer exist so it wasn't wrong. 

Sorry if I overstepped, feel free to revert.

**Pull request merged**
