### PR TITLE
Add special `dautotest` target

### PR DESCRIPTION
**Pull request by wilzbach**
The idea is to make it:

- easy to modify in case of future updates
- easy to spot and understand by contributors to see what's going on with DAutoTest

### CODE REVIEW

**Comment by MetaLang** [comment]
This is trivial so I'm gonna merge without waiting for further input.

**Comment by wilzbach** [comment]
Oh we kinda need @CyberShadow here as he's the maintainer of DAutoTest...

**Comment by MetaLang** [comment]
Oh, I thought this was just adding the target.

**Comment by wilzbach** [comment]
BTW the respective code for DAutoTest is here: https://github.com/CyberShadow/ae/blob/bdc41d1669264104ae38c5919c9a1560d685c4f9/sys/d/manager.d#L1718

So it should have been:

```
dautotest: all verbatim pdf diffable-intermediaries
```

Sorry.

**Comment by wilzbach** [comment]
Anyhow no harm done:

https://github.com/dlang/dlang.org/pull/2035

I actually prefer action with 1 in 20 cases being a bit too eager instead of letting PRs stall for months.

**Comment by MetaLang** [comment]
Yeah, sorry, I'm on mobile so I'm trying to quickly review PRs that look trivial and not let things sit around.

**Pull request merged**
