### PR TITLE
Correct unittest point: with -> without

### PR DESCRIPTION
**Pull request by mathias-baumann-sociomantic**
I suspect that's what was intended?

### CODE REVIEW

**Comment by schveiguy** [comment]
The grammar doesn't make sense, even before the change. I'm not sure what the statement in parentheses is trying to say. Can you explain what it means?

**Comment by schveiguy** [comment]
ping @wilzbach as the original author.

**Comment by schveiguy** [comment]
OK, I think it came from this comment: https://github.com/dlang/dlang.org/pull/1796#discussion_r125882434

So yes, the intent is to say, you can unit test your betterC functions by running without -betterC.

**Comment by wilzbach** [comment]
> I suspect that's what was intended?

Yes, thanks.

>  Can you explain what it means?

The point was to say that `unittest` doesn't work with `-betterC`, but for testing purposes the program can simply compiled and run _without_ `-betterC`.

**Comment by schveiguy** [comment]
Suggestion (correct grammar, and removing superfluous "as usual"): "testing can be done without the `-betterC` flag"

**Comment by wilzbach** [comment]
> Suggestion (correct grammar, and removing superfluous "as usual"): "testing can be done without the -betterC flag"

I changed it to your suggestion. Thanks!

**Pull request merged**
