### PR TITLE
Add winning D-Man to conditional compilation

### PR DESCRIPTION
**Pull request by wilzbach**
Found another lovely D-Man. Author is again [meiz_sandwich](https://twitter.com/meiz_sandwich)

My motivation here is that CTFE is one of the features that make D a _winner_. Otherwise templates could also be used.

image

### CODE REVIEW

**Comment by CyberShadow** [comment]
This seems a little forced

**Comment by WalterBright** [comment]
While a great drawing, I don't think it matches the theme of conditional compilation.

**Comment by wilzbach** [comment]
> While a great drawing, I don't think it matches the theme of conditional compilation.

Fair enough, how about
- [Why D?](http://dlang.org/overview.html) (moving the menu to the left)
- [Builtin rationale](http://dlang.org/builtin.html)
- [Feature overview](http://dlang.org/comparison.html)
- [Lazy evaluation](https://dlang.org/lazy-evaluation.html)

**Comment by wilzbach** [comment]
In any case if someone has a good use for this graphic, please go ahead ;-)

**Pull request closed without merging**
