### PR TITLE
DConf front page: registration is open

### PR DESCRIPTION
**Pull request by wilzbach**

### CODE REVIEW

**Comment by wilzbach** [comment]
CC @CyberShadow this is a rather time-sensitive item for the front page.

**Comment by CyberShadow** [comment]
It's still a bit hidden in a corner, should it be promoted to a banner higher at some point?

**Comment by wilzbach** [comment]
Yeah why not :)
Do you want to use something similar to the "State of D" banner?
We could even make the "D" move a bit (but from the feedback on the proposed [dconf18](https://wilzbach.github.io/dconf18/) website, I'm guessing this wouldn't be popular)

CC @mdparker

**Comment by CyberShadow** [comment]
> We could even make the "D" move a bit

**NO**. Annoying as hell when you're trying to read something else on the same page.

**Pull request merged**
