### PR TITLE
Update Areas of Usage

### PR DESCRIPTION
**Pull request by jansengb**
Remove link to std.experimental.ndslice.

### CODE REVIEW

**Comment by wilzbach** [comment]
I remember that there were some controversy about linking to mir, so leaving this to someone else to merge. Maybe @JackStouffer or @CyberShadow?

**Comment by CyberShadow** [comment]
> I remember that there were some controversy about linking to mir

In the language spec. This is fine IMO.

**Comment by CyberShadow** [comment]
Actually, this is not fine. The text now says that "D includes support for X in a third-party library". That's self-contradicting. Also, D supports a lot of various X-s through third-party libraries, no point in listing them all.

Just remove that paragraph, IMO.

**Comment by jansengb** [comment]
Don't agree to not mentioning mir/ndslices just because there are many other third-party libraries. This library is fundamental for this usage area. How about "There is excellent support for ..."? I'll leave it to someone who can edit the page directly to fix it.

**Comment by wilzbach** [comment]
@jansengb seems like you have trailing whitespace:

```
Searching for trailing whitespace
./areas-of-d-usage.dd:188:    There is excellent support for multidimensional arrays with third-party libraries  
posix.mak:639: recipe for target 'test' failed
```

**Comment by wilzbach** [comment]
> @jansengb seems like you have trailing whitespace:

Removed the trailing whitespace and squashed, s.t. we can move forward here.

**Pull request merged**
