### PR TITLE
Mention the DWiki entry in the README

### PR DESCRIPTION
**Pull request by wilzbach**
I think the wiki entry is poorly referenced - I couldn't find a single link here.
(in general I think that the wiki entry should be merged with the `CONTRIBUTING.md`).

### CODE REVIEW

**Comment by wilzbach** [comment]
> @CyberShadow  added the auto-merge label 6 minutes ago

AFAICT has the DLang Bot still no merge access to the dlang.org repo. So only "manual merge" is possible here :/

**Comment by CyberShadow** [comment]
> AFAICT has the DLang Bot still no merge access to the dlang.org repo.

How can we fix that?

**Comment by CyberShadow** [comment]
Should I just add @dlang-bot to the dlang.org team?

**Comment by wilzbach** [comment]
> How can we fix that?
> Should I just add @dlang-bot to the dlang.org team?

Yep :)

**Comment by CyberShadow** [comment]
@dlang-bot is already part of "Team dlang.org", which grants write access to this repo. So, something else seems to be missing.

**Pull request merged**
