### PR TITLE
Use the latest dependency versions for dpl-docs.

### PR DESCRIPTION
**Pull request by s-ludwig**
This, apart from a number of fixes, will switch to static syntax highlighting instead of relying on prettify.js.

### CODE REVIEW

**Comment by CyberShadow** [comment]
```
Generating module: std.experimental.allocator.common
core.exception.RangeError@../../home/.dub/packages/libdparse-0.5.0/src/dparse/lexer.d(979): Range violation
----------------
??:? _d_arraybounds [0xb09c9b]
??:? dparse.lexer.__array [0x983510]
??:? pure nothrow @safe void dparse.lexer.DLexer.lexIntSuffix(ref ubyte) [0x996dcf]
??:? pure nothrow @trusted void dparse.lexer.DLexer.lexDecimal(ref std.experimental.lexer.TokenStructure!(ubyte, "\x0a    string comment;\x0a    string trailingComment;\x0a\x0a    int opCmp(size_t i) const pure nothrow @safe {\x0a        if (index < i) return -1;\x0a        if (index > i) return 1;\x0a        return 0;\x0a    }\x0a\x0a    int opCmp(ref const typeof(this) other) const pure nothrow @safe {\x0a        return opCmp(other.index);\x0a    }\x0a").TokenStructure, ulong, ulong, ulong, ulong) [0x996b47]
??:? pure nothrow @safe void dparse.lexer.DLexer.lexDecimal(ref std.experimental.lexer.TokenStructure!(ubyte, "\x0a    string comment;\x0a    string trailingComment;\x0a\x0a    int opCmp(size_t i) const pure nothrow @safe {\x0a        if (index < i) return -1;\x0a        if (index > i) return 1;\x0a        return 0;\x0a    }\x0a\x0a    int opCmp(ref const typeof(this) other) const pure nothrow @safe {\x0a        return opCmp(other.index);\x0a    }\x0a").TokenStructure) [0x99697c]
??:? pure nothrow @trusted void dparse.lexer.DLexer.__mixin41.advance(ref std.experimental.lexer.TokenStructure!(ubyte, "\x0a    string comment;\x0a    string trailingComment;\x0a\x0a    int opCmp(size_t i) const pure nothrow @safe {\x0a        if (index < i) return -1;\x0a        if (index > i) return 1;\x0a        return 0;\x0a    }\x0a\x0a    int opCmp(ref const typeof(this) other) const pure nothrow @safe {\x0a        return opCmp(other.index);\x0a    }\x0a").TokenStructure) [0x98d62f]
??:? pure nothrow @safe void dparse.lexer.DLexer.__mixin41._popFront!()._popFront() [0x9423f8]
??:? pure nothrow @safe void dparse.lexer.DLexer.popFront!().popFront() [0x942388]
??:? pure nothrow ref @safe dparse.lexer.DLexer dparse.lexer.DLexer.__ctor(ubyte[], const(dparse.lexer.LexerConfig), dparse.lexer.StringCache*, bool) [0x995d21]
??:? void ddox.highlight.highlightDCodeImpl!(std.array.Appender!(immutable(char)[]).Appender).highlightDCodeImpl(ref std.array.Appender!(immutable(char)[]).Appender, immutable(char)[], scope void delegate(immutable(char)[], scope void delegate()), ref immutable(char)[]) [0x927b2a]
??:? void ddox.highlight.highlightDCode!(std.array.Appender!(immutable(char)[]).Appender).highlightDCode(ref std.array.Appender!(immutable(char)[]).Appender, immutable(char)[], scope void delegate(immutable(char)[], scope void delegate())) [0x927a11]
??:? immutable(char)[] ddox.highlight.highlightDCode(immutable(char)[], void delegate(immutable(char)[], scope void delegate())) [0x95e43b]
??:? _D4vibe5templ4diet649__T21compileDietFileIndentVAyaa15_64646f782e646f63706167652e6474Vii0S287_D4ddox13htmlgenerator16generateDeclPageFC4vibe4core6stream12OutputStreamC4ddox8entities7PackageC4ddox8entities6ModuleAyaAC4ddox8entities8DocGroupC4ddox8settings17GeneratorSettingsDFC4ddox8entities6EntityZAyaC4vibe4http6server17HTTPServerRequestZ3reqC4vibe4http6server17HTTPServerRequestS285_D4ddox13htmlgenerator16generateDeclPageFC4vibe4core6stream12OutputStreamC4ddox8entities7PackageC4ddox8entities6ModuleAyaAC4ddox8entities8DocGroupC4ddox8settings17GeneratorSettingsDFC4ddox8entities6EntityZAyaC4vibe4http6server17HTTPServerRequestZ4infoC4ddox13htmlgenerator11DocPageInfoZ21compileDietFileIndentMFC4vibe4core6stream12OutputStreamZ25outputVariableDescriptionMFC4ddox8entities11DeclarationZv [0x93bf27]
??:? void vibe.templ.diet.compileDietFileIndent!("ddox.docpage.dt", 0, vibe.http.server.HTTPServerRequest ddox.htmlgenerator.generateDeclPage(vibe.core.stream.OutputStream, ddox.entities.Package, ddox.entities.Module, immutable(char)[], ddox.entities.DocGroup[], ddox.settings.GeneratorSettings, immutable(char)[] delegate(ddox.entities.Entity), vibe.http.server.HTTPServerRequest).req, ddox.htmlgenerator.DocPageInfo ddox.htmlgenerator.generateDeclPage(vibe.core.stream.OutputStream, ddox.entities.Package, ddox.entities.Module, immutable(char)[], ddox.entities.DocGroup[], ddox.settings.GeneratorSettings, immutable(char)[] delegate(ddox.entities.Entity), vibe.http.server.HTTPServerRequest).info).compileDietFileIndent(vibe.core.stream.OutputStream) [0x93693e]
??:? void vibe.templ.diet.compileDietFile!("ddox.docpage.dt", vibe.http.server.HTTPServerRequest ddox.htmlgenerator.generateDeclPage(vibe.core.stream.OutputStream, ddox.entities.Package, ddox.entities.Module, immutable(char)[], ddox.entities.DocGroup[], ddox.settings.GeneratorSettings, immutable(char)[] delegate(ddox.entities.Entity), vibe.http.server.HTTPServerRequest).req, ddox.htmlgenerator.DocPageInfo ddox.htmlgenerator.generateDeclPage(vibe.core.stream.OutputStream, ddox.entities.Package, ddox.entities.Module, immutable(char)[], ddox.entities.DocGroup[], ddox.settings.GeneratorSettings, immutable(char)[] delegate(ddox.entities.Entity), vibe.http.server.HTTPServerRequest).info).compileDietFile(vibe.core.stream.OutputStream) [0x93503c]
??:? void ddox.htmlgenerator.generateDeclPage(vibe.core.stream.OutputStream, ddox.entities.Package, ddox.entities.Module, immutable(char)[], ddox.entities.DocGroup[], ddox.settings.GeneratorSettings, immutable(char)[] delegate(ddox.entities.Entity), vibe.http.server.HTTPServerRequest) [0x92a0f5]
??:? _D4ddox13htmlgenerator16generateHtmlDocsFS4vibe4inet4path4PathC4ddox8entities7PackageC4ddox8settings17GeneratorSettingsZ11visitModuleMFC4ddox8entities6ModuleS4vibe4inet4path4PathZ14__foreachbody5MFKAyaKAC4ddox8entities8DocGroupZ47__T9__lambda3TC4vibe4core6stream12OutputStreamZ9__lambda3MFC4vibe4core6stream12OutputStreamZv [0x9293c7]
??:? void ddox.htmlgenerator.generateHtmlDocs(vibe.inet.path.Path, ddox.entities.Package, ddox.settings.GeneratorSettings).writeHashedFile(vibe.inet.path.Path, scope void delegate(vibe.core.stream.OutputStream)) [0x928ebe]
??:? _D4ddox13htmlgenerator16generateHtmlDocsFS4vibe4inet4path4PathC4ddox8entities7PackageC4ddox8settings17GeneratorSettingsZ11visitModuleMFC4ddox8entities6ModuleS4vibe4inet4path4PathZ14__foreachbody5MFKAyaKAC4ddox8entities8DocGroupZi [0x92937f]
??:? _aaApply2 [0xb0f50c]
??:? void ddox.htmlgenerator.generateHtmlDocs(vibe.inet.path.Path, ddox.entities.Package, ddox.settings.GeneratorSettings).visitModule(ddox.entities.Module, vibe.inet.path.Path) [0x929200]
??:? void ddox.htmlgenerator.generateHtmlDocs(vibe.inet.path.Path, ddox.entities.Package, ddox.settings.GeneratorSettings).visitPackage(ddox.entities.Package, vibe.inet.path.Path) [0x9295cb]
??:? void ddox.htmlgenerator.generateHtmlDocs(vibe.inet.path.Path, ddox.entities.Package, ddox.settings.GeneratorSettings).visitPackage(ddox.entities.Package, vibe.inet.path.Path) [0x929555]
??:? void ddox.htmlgenerator.generateHtmlDocs(vibe.inet.path.Path, ddox.entities.Package, ddox.settings.GeneratorSettings).visitPackage(ddox.entities.Package, vibe.inet.path.Path) [0x929555]
??:? void ddox.htmlgenerator.generateHtmlDocs(vibe.inet.path.Path, ddox.entities.Package, ddox.settings.GeneratorSettings).visitPackage(ddox.entities.Package, vibe.inet.path.Path) [0x929555]
??:? void ddox.htmlgenerator.generateHtmlDocs(vibe.inet.path.Path, ddox.entities.Package, ddox.settings.GeneratorSettings) [0x92862d]
??:? int ddox.main.cmdGenerateHtml(immutable(char)[][]) [0x8d3ca9]
??:? int ddox.main.ddoxMain(immutable(char)[][]) [0x8d3ad1]
??:? _Dmain [0x8d1f91]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0xb10d6e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xb10cc4]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0xb10d2a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xb10cc4]
??:? _d_run_main [0xb10c21]
??:? main [0x8d38c5]
??:? __libc_start_main [0xae504ec4]
make: *** [/home/dtest/DAutoTest/work/repo/dlang.org/web/library/sitemap.xml] Error 1
make: *** Deleting file `/home/dtest/DAutoTest/work/repo/dlang.org/web/library/sitemap.xml'
Build failed: object.Exception@ae/sys/d/manager.d(673): Command ["make", "-f", "posix.mak", "all", "kindle", "pdf", "verbatim", "NODATETIME=nodatetime.ddoc", "LATEST=2.071.0"] failed with status 2
```

**Comment by s-ludwig** [comment]
Okay, looks good now.

**Comment by CyberShadow** [comment]
Looks good. Though, `int` and `void` are now not highlighted as keywords?

**Comment by s-ludwig** [comment]
Working on fixes for those issues.

**Pull request merged**
