### PR TITLE
Fix DDOX documentation top page links and MYREF references.

### PR DESCRIPTION
**Pull request by s-ludwig**

### CODE REVIEW

**Comment by CyberShadow** [comment]
```
core.exception.AssertError@../../home/.dub/packages/vibe-d-0.7.28/source/vibe/http/server.d(703): null this
```

**Comment by s-ludwig** [comment]
Okay, looks good now.

**Comment by andralex** [comment]
Alrighty, thanks! @CyberShadow I'll pull lmk if any objections. @wilzbach do we have that snazzy auto-release upon pull thing?

**Comment by CyberShadow** [comment]
> Alrighty, thanks! @CyberShadow I'll pull lmk if any objections.

Was just about to pull it myself.

> @wilzbach do we have that snazzy auto-release upon pull thing?

Worked on it a bit yesterday.

**Comment by wilzbach** [comment]
> @wilzbach do we have that snazzy auto-release upon pull thing?

Yep unfortunately I can't help much there, (because of the access-right), but if I can let me know @CyberShadow!

**Comment by CyberShadow** [comment]
> @wilzbach do we have that snazzy auto-release upon pull thing?

OK, it's live now.

**Pull request merged**
