### PR TITLE
Reworded statement

### PR DESCRIPTION
**Pull request by brdjns**
Reworded the initial statement under the 'Convenience' heading of the 'Why D?' section. The language flows better with the combination of a subject pronoun + verb infinitive, than with just a verb in the present participle form. Addressing the reader directly promotes a sense of inclusion in the action suggested.

### CODE REVIEW

**Comment by CyberShadow** [comment]
Not to nitpick on such a small change and especially as someone with English as their third language, but I thought we were generally avoiding using "you" and second person in general.

**Comment by wilzbach** [comment]
> Not to bikeshed on such a small change and especially as someone with English as their third language, but I thought we were generally avoiding using "you" and second person in general.

Yep I also thought that a neutral tone should be used for the specification. Even for the Dlang tour we have defined [such rules](https://github.com/stonemaster/dlang-tour/blob/master/CONTRIBUTING.md#writing-style-guide), maybe we should do the same in the `CONTRIBUTING.md` for dlang.org?

**Comment by AndrejMitrovic** [comment]
That makes three of us, I think it's a step in the wrong direction. 

> Even for the Dlang tour we have defined such rules, maybe we should do the same in the CONTRIBUTING.md for dlang.org?

Sounds good. In the meantime closing this.

**Comment by wilzbach** [comment]
>>> I thought we were generally avoiding using "you" and second person in general.
>> Even for the Dlang tour we have defined such rules, maybe we should do the same in the CONTRIBUTING.md for dlang.org?
> Sounds good. In the meantime closing this.

-> #1448

**Pull request closed without merging**
