### PR TITLE
Upgrade to DDOX 0.15.1.

### PR DESCRIPTION
**Pull request by s-ludwig**
- Fixes parsing function with auto return type and this modifiers
- Fixes duplicated symbols being output to doc pages and to the file system
- Fixes lookup of variadic template arguments

### CODE REVIEW

**Comment by CyberShadow** [comment]
```
Generating module: std.experimental.ndslice.slice
make: *** [/home/dtest/DAutoTest/work/repo/dlang.org/web/library/sitemap.xml] Segmentation fault (core dumped)
```
Whoops

**Comment by s-ludwig** [comment]
Fixed. Will probably run into the meta data cache issue now.

**Comment by CyberShadow** [comment]
> Will probably run into the meta data cache issue now.

I thought https://github.com/dlang/dlang.org/commit/e9af9432d5752941c70304c779ac495838d0cc33 was supposed to fix that?

It seems to work so far...

**Comment by CyberShadow** [comment]
Ahh, I love all that red!

**Comment by s-ludwig** [comment]
Oh right, completely forgot about that already...

**Pull request merged**
