### PR TITLE
fix Issue 16167 - chm-nav.json generation is broken

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
Testing the fix currently.

**Comment by MartinNowak** [comment]
Retry

We really should waste less time on such things as generating json using ddoc.

**Comment by CyberShadow** [comment]
Sorry about that :)

**Comment by MartinNowak** [comment]
> Sorry about that :)

Not your fault, but maybe we can generate chm from the html output directly? Or just ditch it?
It's 2016, who needs installed websites anyhow?

**Comment by CyberShadow** [comment]
> Not your fault, but maybe we can generate chm from the html output directly? 

It's needed to generate the navigation, which is metadata.

> Or just ditch it?

Every time we ask, a few people raise their hands. The bigger advantages are the search and index. Maybe DDox will make it less necessary.

**Comment by MartinNowak** [comment]
> Every time we ask, a few people raise their hands.

Sure, people don't want to change their habits, but we could do it anyhow.
If search in chm works better than on our website, than we need to fix the latter, let's ask again.

**Comment by MartinNowak** [comment]
Seems to work now.

**Pull request merged**
