### PR TITLE
Fix link to FuncDeclarator

### PR DESCRIPTION
**Pull request by wilzbach**
@CyberShadow any smart idea on easily verifying that all links are valid?
The ugly way would be to parse the generated HTML, create name/id lists for each file and then check all links ...

### CODE REVIEW

**Comment by CyberShadow** [comment]
> Thanks for your pull request, @wilzbach! We are looking forward to reviewing it, and you should be hearing from a maintainer soon.

Oh, what is this?

**Comment by CyberShadow** [comment]
> The ugly way would be to parse the generated HTML, create name/id lists for each file and then check all links ...

That's the way.

chmgen already does it BTW.

**Comment by wilzbach** [comment]
> Oh, what is this?

-> https://github.com/dlang-bots/dlang-bot/pull/44

The idea is to always "reserve" the first comment and update it with helpful information.
We are still at the beginning and it's not super helpful (yet), but this is deployed:
- hello world message
- [warning about a regression PR not targeted at stable](https://github.com/dlang-bots/dlang-bot/pull/57)

Anyways, there's [more to come](https://github.com/dlang-bots/dlang-bot/issues/8).

If you want to change the text -> https://github.com/dlang-bots/dlang-bot/blob/master/source/dlangbot/github.d#L57

**Comment by ZombineDev** [comment]
(Closing & reopening in order to restart the CI.)

**Comment by ZombineDev** [comment]
@CyberShadow @wilzbach can you guys add a "Ddoc bug fix" label? The intent is to tag pull requests that fix ddoc errors (such as this one) but don't otherwise deserve a Bugzilla entry.

**Comment by wilzbach** [comment]
@ZombineDev You can add them yourself - click on labels on the pull requests overview list...

**Comment by ZombineDev** [comment]
@wilzbach Thanks, not sure how I missed it.

**Pull request merged**
