### PR TITLE
The foundation is tax-exempt

### PR DESCRIPTION
**Pull request by schveiguy**
We should proudly share that info!

### CODE REVIEW

**Comment by JackStouffer** [comment]
As this is a static page, it would make more sense to frame it as a statement of fact rather than an announcement IMO.

**Comment by schveiguy** [comment]
It can be changed to something different. I wanted to put some sort of positive exclamation in there, and this is the only thing I could think of that sounded reasonable. Any other ideas?

**Comment by CyberShadow** [comment]
@andralex

**Comment by schveiguy** [comment]
Thanks!

**Pull request merged**
