### PR TITLE
add Auburn Sounds to orgs-using-d

### PR DESCRIPTION
**Pull request by wilzbach**
CC @p0nce 

(SVG is added in case we need a nigher quality image)

### CODE REVIEW

**Comment by p0nce** [comment]
Thanks for doing this!

**Comment by CyberShadow** [comment]
The gzipped SVG is smaller than the PNG. Why bother with the PNG?

**Comment by wilzbach** [comment]
> The gzipped SVG is smaller than the PNG. Why bother with the PNG?

@p0nce added some specific shading to the PNG...

**Comment by p0nce** [comment]
It looked bad on a white background.

**Comment by CyberShadow** [comment]
I thought the _hq versions are so we can easily recreate the non-_hq versions when we switch to a different size...

**Comment by p0nce** [comment]
I'll fix it if you switch to a different size.

**Pull request merged**
