### PR TITLE
Point user to std.array.byPair if compatibility with Tuple is desired.

### PR DESCRIPTION
**Pull request by quickfur**
Based on [forum feedback](http://forum.dlang.org/post/osbkmrvyqqjjsxyzgcyd@forum.dlang.org).

### CODE REVIEW

**Comment by wilzbach** [comment]
Though I am wondering why no one has bothered to implement `opApply` for `.byKeyValue`

I could only find this discussion (https://github.com/dlang/druntime/pull/1070), but no mention of reasons against it.

**Comment by quickfur** [comment]
@wilzbach Why would that be necessary?  `.byKeyValue` works fine inside a `foreach` loop.
````
int[string] aa;
aa["abc"] = 1;
aa["def"] = 2;
foreach (p; aa.byKeyValue) {
    writefln("%s: %s", p.key, p.value);
}
````

**Comment by wilzbach** [comment]
> @wilzbach Why would that be necessary? .byKeyValue works fine inside a foreach loop.

I was referring to an `opApply(K, V)(K k, V v)` with two parameters because that would have covered most cases for which `byPair` is used ;-)

**Comment by quickfur** [comment]
But why? This works just fine:
````
int[string] aa = ...;
foreach (key, value; aa) {
    writefln("%s: %s", key, value);
}
````

**Comment by wilzbach** [comment]
> But why? This works just fine:

Oh I think I got totally confused, sorry.
-> I made an enhancement request to the specs to show an example of this to the reader:

https://github.com/dlang/dlang.org/pull/1577

**Pull request merged**
