### PR TITLE
Try to move GSOC files into their own folder

### PR DESCRIPTION
**Pull request by maxhaton**
First step to trying to clear up the dlang.org tree.

It's a mess.

### CODE REVIEW

**Comment by thewilsonator** [comment]
`dmd/src/dmd` next pls.

**Comment by maxhaton** [comment]
> `dmd/src/dmd` next pls.

https://youtu.be/CZ44w8DMxJw 
That's fightin' talk boy

**Comment by CyberShadow** [comment]
@maxhaton @thewilsonator  This broke the pages:

https://dlang.org/gsoc/gsoc2012.html

You need to update the macro which sets the site root, so that the resources (CSS) are loaded from the correct location.

(Not that I expect that these pages are going to be in high demand, but we should either keep them non-broken or delete them outright.)

**Comment by maxhaton** [comment]
> @maxhaton @thewilsonator This broke the pages:
> 
> https://dlang.org/gsoc/gsoc2012.html
> 
> You need to update the macro which sets the site root, so that the resources (CSS) are loaded from the correct location.
> 
> (Not that I expect that these pages are going to be in high demand, but we should either keep them non-broken or delete them outright.)

Ok. Ddoc is awful...

I'll rectify this, could you make DAutoTester try to catch this? Maybe it already does but failed to go red?

**Comment by CyberShadow** [comment]
Yeah, it catches some things but not this case apparently.

Search for "Warning:" in the build log. I see it has bitrotten and reports all pages as false positives today though.

**Pull request merged**
