### PR TITLE
Add D-Man to DateTime article

### PR DESCRIPTION
**Pull request by wilzbach**
Found another lovely D-Man. Author is again [meiz_sandwich](https://twitter.com/meiz_sandwich)

Ping @jmdavis 

image

### CODE REVIEW

**Comment by Hackerpilot** [comment]
@wilzbach: Merge conflicts.

**Comment by wilzbach** [comment]
> @wilzbach: Merge conflicts.

Fixed ;-)

**Comment by wilzbach** [comment]
Ping @WalterBright for approval.

**Comment by AndrejMitrovic** [comment]
What's with the `needs-approval`? This is great, merging this in.

**Pull request merged**
