### PR TITLE
Remove 'State of D' survey banner

### PR DESCRIPTION
**Pull request by wilzbach**
To be merged on Wednesday, 14.3

### CODE REVIEW

**Comment by wilzbach** [comment]
As it turns out, we already have a new item for the highlighted news area - the Amazon Smile promotion.
I already added this to this PR to avoid merge conflicts:

image

**Comment by JackStouffer** [comment]
I'm not really sure about this. The turquoise really sticks out from the rest of the page.

Can we put this on the donate page or redesign it to be less obtrusive?

What do you think @CyberShadow?

**Comment by wilzbach** [comment]
> redesign it to be less obtrusive?

How about something like the existing banner?

amazon-smile-banner

or:

open-collective-launchedpng

**Comment by CyberShadow** [comment]
I think the banner is OK, considering it's temporary.

**Comment by wilzbach** [comment]
@JackStouffer the plan is to swap this tonight, so if you have a better idea, please let me know.

**Comment by JackStouffer** [comment]
If it's temporary I'm ok with it.

**Pull request merged**
