### PR TITLE
index.dd: Pre-populate subject line for "your code here" submissions

### PR DESCRIPTION
**Pull request by CyberShadow**
DFeed change: https://github.com/CyberShadow/DFeed/commit/c3199d6a01887974345d3f0f72eee1f982419e9c

### CODE REVIEW

**Comment by ZombineDev** [comment]
LGTM

**Comment by wilzbach** [comment]
LGTM^2

**Comment by wilzbach** [comment]
Any reason why we haven't rolled this out yet? 
It's a simple change & if I could, I would merge it ;-)

**Comment by andralex** [comment]
New code should use `HTTP` :o)

**Comment by adamdruppe** [comment]
Please kill `HTTP` and `HTTPS`, they aren't worth the cache space in the brain compared to just pasting the link into a `LINK2` (especially since copy/past from the browser URL bar will likely add the `https://` automatically anyway, so to use `HTTPS`, you'd have to manually edit it after checking for 404's, which is liable to introduce broken link errors.)

**Pull request merged**
