### PR TITLE
Fix a link and typo in the changelog

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by MartinNowak** [comment]
Should've been on stable!!!

**Comment by wilzbach** [comment]
> Should've been on stable!!!

Why? Afaik Master gets directly deployed because we want to avoid a stalled web page

**Comment by MartinNowak** [comment]
> Why? Afaik Master gets directly deployed because we want to avoid a stalled web page

Because documentation incorporated into releases is build from stable. You can merge back stable into master as often as you want.

**Comment by 9il** [comment]
PR for stable: #1496

**Pull request merged**
