### PR TITLE
Fix AA word count example

### PR DESCRIPTION
**Pull request by ntrel**
Add Examples heading otherwise they're listed under Properties.
Make example get compiled.
Add missing import.

### CODE REVIEW

**Comment by ntrel** [comment]
I think the example would be clearer if it worked on `stdin` rather than accepting multiple filenames and opening each. It's supposed to demonstrate AAs rather than how to implement a command-line program. Happy to do that if anyone else agrees.

**Comment by ntrel** [comment]
@CyberShadow Is there a limit on compilable example length? It seems to be getting cut off in the middle of a string literal.
```
                if (args.length > 2)
                {
                    writefln("
---
__stdin.d(64): Error: unterminated string constant starting at __stdin.d(64)
```
The example runs on clicking run in my local generated html file.

**Comment by CyberShadow** [comment]
The problem has to be the string of `-------------------------------------`. There's probably a bug somewhere, it should be looking only at the start of the line and optional whitespace.

**Comment by ntrel** [comment]
Tests now green.

**Review by dkorpel — APPROVED** [review]

**Pull request merged**
