### PR TITLE
Update release year found in download link

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
The new release wasn't found because of wrong year

### CODE REVIEW

**Comment by MoonlightSentinel** [comment]
@ibuclaw Ready

**Comment by MoonlightSentinel** [comment]
When will this be published to `dlang.org`?

**Comment by ibuclaw** [comment]
> When will this be published to `dlang.org`?

I'll check if there is something in crontab, IIRC it is periodic.

**Comment by MoonlightSentinel** [comment]
Thanks!

**Comment by ibuclaw** [comment]
> Thanks!

The verbatim links have been updated, but the html hasn't.  Any idea @CyberShadow?
https://dlang.org/download.verbatim

**Comment by CyberShadow** [comment]
dlang.org is deployed from master, not stable.

**Comment by MoonlightSentinel** [comment]
> dlang.org is deployed from master, not stable.

This should probably be mentioned in the README

> Not sure why we even have a stable branch here.

Maybe we should remove the branch if it serves no purpose?

**Pull request merged**
