### PR TITLE
Document extern(C++, class) and extern(C++, struct)

### PR DESCRIPTION
**Pull request by JohanEngelen**

### CODE REVIEW

**Comment by mathias-lang-sociomantic** [comment]
Thanks !
You'll also need to update `spec/grammar.dd` (`LinkageAttribute`).
Also, you might want to add a precision that multiple `extern (C++, XXX)` can be combined, e.g. an example with an `extern(C++, struct)` in a namespace.

**Comment by JohanEngelen** [comment]
(please just pull and submit new PRs for additional doc, thanks)

**Comment by mathias-lang-sociomantic** [comment]
The second one I can understand, but the `LinkageAttribute` should go on par with this change IMO

**Comment by redstar** [comment]
@JohanEngelen Thanks for doing this PR!

IMHO it would be good to add an introductory sentence, e.g.

"D structs and classes have different semantics whereas C++ structs and classes are basically the same. The use of a D struct or class depends on the C++ implementation and not on the used C++ keyword."

Otherwise LGTM.

**Comment by JohanEngelen** [comment]
I am not going to maintain this PR. It is a drive-by contribution to dlang. Merge it, or close it. Either is fine by me.

**Comment by CyberShadow** [comment]
@redstar @mathias-lang-sociomantic Merge or close?

**Comment by redstar** [comment]
Merge. I create a separate PR with my addition.

**Pull request merged**
