### PR TITLE
include osmodel.mak from tools repo

### PR DESCRIPTION
**Pull request by wilzbach**
I realized that it's quite hard to get an outdated file, if there's only one and as we already require the `dmd` repo, we can directly use the `osmodel.mak` file from there. It rarely changes.

https://github.com/dlang/druntime/pull/1780
https://github.com/dlang/phobos/pull/5228
https://github.com/dlang/tools/pull/227

edit: rebased to use `tools` instead

### CODE REVIEW

**Comment by braddr** [comment]
We don't already require the dmd repo, we require a dmd executable, very different things.  Please don't add cross package dependencies like this.  The same applies to the other changes that are adding git clone and similar cross package dependencies.. just don't.

**Comment by CyberShadow** [comment]
@braddr What does your autotester have to do with the dlang.org repo though? The documentation tester does in fact require the DMD repo because we build documentation for the DMD source code.

**Comment by wilzbach** [comment]
> Please don't add cross package dependencies like this. The same applies to the other changes that are adding git clone and similar cross package dependencies.. just don't.

Have you had a recent look at the `posix.mak` here?
The "cross-package" have existed since ages ...

https://github.com/dlang/dlang.org/blob/master/posix.mak#L350

To build `dlang.org` one needs to clone `dmd`, `druntime`, `phobos` and `tools`, so I honestly don't see the issue.

FYI: As suggested on the other PRs, I changed the "one source of truth" to `tools`.

**Comment by braddr** [comment]
Apologies, the straw that pushed me into objecting to the cross package dependency changes turned out to be the one that was already so deep in that hole that another hardly matters.  The objection still holds for the others and if you need me to, I'll repeat myself across each of them.

**Comment by wilzbach** [comment]
> The objection still holds for the others and if you need me to, I'll repeat myself across each of them.

Discussions are at:

https://github.com/dlang/tools/pull/227
https://github.com/dlang/dmd/pull/6584

Maybe we move this discussion to the internal ML, s.t. you don't need to repeat yourself ;-)

**Comment by wilzbach** [comment]
Superseded by https://github.com/dlang/dlang.org/pull/1791

**Pull request closed without merging**
