### PR TITLE
Fix issue 16464. Define more clearly opCast usage

### PR DESCRIPTION
**Pull request by schveiguy**

### CODE REVIEW

**Comment by TurkeyMan** [comment]
I'd like it to be stated that this only applies to explicit uses of the cast operator.
C++ cast operators are implicit (unless the `explicit` keyword is given), and people find this D behaviour surprising.

**Comment by TurkeyMan** [comment]
LGTM

**Comment by AndrejMitrovic** [comment]
Please squash and I'll merge.

**Comment by schveiguy** [comment]
@AndrejMitrovic squashed

**Comment by AndrejMitrovic** [comment]
Thanks!

**Pull request merged**
