### PR TITLE
Add a simple overview of all contributors

### PR DESCRIPTION
**Pull request by wilzbach**
Add initial list of all contributors. This is just as a start to explore options on how we could utilize this information from the git log.

Depends on https://github.com/dlang/tools/pull/253

### CODE REVIEW

**Comment by wilzbach** [comment]
Rebased and reworked, s.t. it can be used with the now merged (https://github.com/dlang/tools/pull/253) contributor query script.
Preview:

image

The number is a bit off as there probably are still duplicates. See also: https://github.com/dlang/tools/pull/270

**Comment by CyberShadow** [comment]
Why the CircleCI failure?

```
fatal: Cannot change to '/home/ubuntu/tools/../installer': No such file or directory
object.Exception@../tools/contributors.d(78): Failed to execute '"git" "-c" "mailmap.file=/home/ubuntu/tools/.mailmap" "-C" "/home/ubuntu/tools/../installer" "log" "--use-mailmap" "--pretty=format:%aN|%aE" "master"'.
```

**Comment by wilzbach** [comment]
> Looks like it's trying to get installer contributions but it's not being cloned.

Yeah seems like I didn't add it as order-only dependency. Done now.

**Comment by CyberShadow** [comment]
Should this be in the navigation? "Community" menu, above "Foundation" maybe?

**Comment by wilzbach** [comment]
> Should this be in the navigation? "Community" menu, above "Foundation" maybe?

Done & resolved the merge conflict.

**Comment by MartinNowak** [comment]
Using shallow clones is a common optimization in build and CI systems, so querying the full git history of branch that might not even be available doesn't work too well.
We could check-in the generated contributors.dd and sort+merge+dedup it with the available history.
Any other ideas?

**Comment by CyberShadow** [comment]
> Any other ideas?

Query the GitHub API or set up a self-hosted service which keeps the full history.

**Comment by MartinNowak** [comment]
Apparently there is already http://contribs.dlang.io/ for phobos docs, though it's blocked by Privacy Badger.

**Comment by MartinNowak** [comment]
Let's try https://github.com/dlang/dlang.org/pull/2015 so I can finally build the beta.

**Pull request merged**
