### PR TITLE
Add dconf info to front page

### PR DESCRIPTION
**Pull request by mdparker**
This adds the DConf '22 logo and relevant links to the front page.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]
This should probably target stable

**Comment by mdparker** [comment]
@thewilsonator Which gets pushed to the live site? Stable?

**Comment by thewilsonator** [comment]
no idea. @CyberShadow ?

**Comment by CyberShadow** [comment]
No, dlang.org does not have a stable branch. Or if it does, it's completely by mistake and it should probably be deleted.

**Comment by thewilsonator** [comment]
> Or if it does

It does.

**Pull request merged**
