### PR TITLE
Document Markdown features in Ddoc

### PR DESCRIPTION
**Pull request by dgileadi**

### CODE REVIEW

**Comment by dgileadi** [comment]
Sorry @thewilsonator I realized I wrote the documentation expecting `-preview=markdown` to be enabled, but I haven't yet made a PR to enable it for dlang.org. So I modified this PR to render correctly without `-preview=markdown` and that toggled off auto-merge.

**Comment by ZombineDev** [comment]
@dgileadi The documentation build failed during the step producing a pdf from latex. As the error message is fairly unhelpful:

```
...


[578]

LaTeX Warning: Hyper reference `text_emphasis' on page 579 undefined on input l
ine 29435.

! Missing $ inserted.
<inserted text> 
                $
l.29455 snake_
              case names and underscore prefix processing in identifier emph...

? 
! Emergency stop.
<inserted text> 
                $
l.29455 snake_
              case names and underscore prefix processing in identifier emph...

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on .generated/dlangspec.log.
posix.mak:546: recipe for target '/dev/shm/dtest/work/repo/dlang.org/web/dlangspec.pdf' failed
make: *** [/dev/shm/dtest/work/repo/dlang.org/web/dlangspec.pdf] Error 1
fatal: 'refs/ae-sys-d-cache/website-d9c9c36b7da8607fe7e9709ab515781281185f10-51018fdd336fbb52d62ce4b54612a0ba' - not a valid ref
[2019-04-18 06:16:33.156962] dautotest: Saving to cache.
[2019-04-18 06:16:33.269103] dautotest: Website build ID: website-d9c9c36b7da8607fe7e9709ab515781281185f10-51018fdd336fbb52d62ce4b54612a0ba
Build failed: object.Exception@ae/sys/d/manager.d(850): Command ["timeout", "1800", "make", "-f", "posix.mak", "DIFFABLE=1", "dautotest"] failed with status 2
----------------
```

I would suggest building locally and doing a binary search on the part that triggers the error.

**Comment by thewilsonator** [comment]
You now have an error somewhere. Where, I have no idea. Ping me when you fix it.

**Comment by dgileadi** [comment]
@thewilsonator looks like I was able to fix it.

**Pull request merged**
