### PR TITLE
Fix auto-deploy due to missing osmodel.mak

### PR DESCRIPTION
**Pull request by wilzbach**
See also: https://github.com/dlang/phobos/pull/5534#issuecomment-312745191

CC @CyberShadow

### CODE REVIEW

**Comment by CyberShadow** [comment]
Thing is that if this fix was needed, then DAutoTest should be failing. But it's not. Argh.

**Comment by CyberShadow** [comment]
ARGH. I know what it is.

`git clean -fdx` ignores submodules, and we put an entire repo in there

**Comment by CyberShadow** [comment]
Log looks good so far!

**Comment by wilzbach** [comment]
> Log looks good so far!

:tada: - glad that it worked :)

**Comment by CyberShadow** [comment]
Thanks for the quick fix!

**Comment by andralex** [comment]
thanks for the frenetic pace you guys

**Pull request merged**
