### PR TITLE
Add sponsors page.

### PR DESCRIPTION
**Pull request by mdparker**

### CODE REVIEW

**Comment by JackStouffer** [comment]
Haven't there been large donations from people who wish to remain anonymous? Can we add a note about that?

**Comment by mdparker** [comment]
@wilzbach 
> New pages need to be added in the Makefile (quickly did that for you)

Thanks. I had done that with my original changes a couple weeks ago. I uploaded the whole site at https://dlang-edits.netlify.com/sponsors.html for some feedback. Then today, before pushing it, I managed to wipe all of my changes when I did a rebase. The sponsors.dd file was still there of course, but I had to go back and add again the menu item and the link on the donations page. Forgot the makefile.

Seems I still have a lot to learn about git.

**Comment by mdparker** [comment]
@JackStouffer Good idea.

**Comment by wilzbach** [comment]
>  I uploaded the whole site at https://dlang-edits.netlify.com/sponsors.html for some feedback. 

FYI: DAutoTest will automatically generate such a preview for you, though I guess in your case you wanted the page to stay hidden until you got all permissions.

Typically it would be http://dtest.dlang.io/results/2bef24b80c07bf05bd07aabe2b1d0c70c0b9c6ac/1e2b3cd52e75141b779ef20eb715c81dbb604d76/ (but today `dtest.dlang.io` is down)

**Comment by wilzbach** [comment]
> @JackStouffer Good idea.

@mdparker FYI (before you do it yourself), have a look at @JackStouffer's suggestion: https://github.com/dlang/dlang.org/pull/2063

**Pull request merged**
