### PR TITLE
Purge the .sort and .reverse array properties

### PR DESCRIPTION
**Pull request by kuettler**
Those are gone in 2.075.0

### CODE REVIEW

**Comment by schveiguy** [comment]
This should have gone into stable, no?

**Comment by wilzbach** [comment]
> This should have gone into stable, no?

Master is automatically deployed. Maybe we should get rid of master here to about the constant confusion. What do you think @CyberShadow?

**Comment by CyberShadow** [comment]
Sorry, I don't understand what you mean. "get rid of master"?

**Comment by wilzbach** [comment]
> Sorry, I don't understand what you mean. "get rid of master"?

Sorry for the sloppy language. I was referring to removing the master branch and setting stable as default

**Comment by ZombineDev** [comment]
I guess that would be the same as removing the `stable` branch. @MartinNowak do we really need stable here? For the release archives, can we just bundle the latest master?

**Comment by CyberShadow** [comment]
I think that would cause more problems than it would solve.

Essentially the `stable` branch should only be targeted for changes that should make it into the included HTML documentation of point-releases. `master` affects the documentation of DMD/Phobos `master`. One branch would mean that either we're completely unable to update the documentation of point-releases, or changes in git `master` would end up in the documentation of point-releases.

**Comment by MetaLang** [comment]
@schveiguy you're right, I need to start paying better attention to which branch is being targeted. I can make a PR tonight to to add this to stable as well.

**Comment by schveiguy** [comment]
> Master is automatically deployed.

To dlang.org? That's not right, it should be stable that's automatically deployed!

Vladimir is right, stable should match stable branches of other repos, master should match master.

**Comment by ZombineDev** [comment]
@schveiguy

> That's not right, it should be stable that's automatically deployed!

Meaning that either:
* We should wait 3 months between updates to the website for new features (e.g. runnable examples, new articles, etc.)
* All web development should happen in stable

**Comment by schveiguy** [comment]
No, what I mean is that dlang.org master should track the master branch of the various tools, stable should track the current release (including the current compiler release).

If master of dlang.org is what is deployed on the actual web site, then the docs don't match what people actually download.

**Pull request merged**
