### PR TITLE
Add pleading D-Man to Exception Safety

### PR DESCRIPTION
**Pull request by wilzbach**
Found another lovely D-Man. Author is again [meiz_sandwich](https://twitter.com/meiz_sandwich)

I liked this one too, and I think a pleading D-man fits to exceptions, but again I am open for better suggestions.

image

### CODE REVIEW

**Comment by CyberShadow** [comment]
Not sure about this one and some of the others. I guess I'll leave it up to Walter :)

**Comment by WalterBright** [comment]
It doesn't seem like it hits the target. In any case, need permission from the artist.

**Comment by wilzbach** [comment]
> It doesn't seem like it hits the target. In any case, need permission from the artist.

We have the permission from the author. As this got a couple of votes, so I leave the decision to @WalterBright. Please approve or close ;-)

**Comment by wilzbach** [comment]
> It doesn't seem like it hits the target. In any case, need permission from the artist.

Okay seems like no one raised an voice for this image -> closing.

**Pull request closed without merging**
