### PR TITLE
Add thin D-man to slices and arrays

### PR DESCRIPTION
**Pull request by wilzbach**
Found another lovely D-Man. Author is again [meiz_sandwich](https://twitter.com/meiz_sandwich)

Ping @schveiguy 

image

I wasn't sure whether this fits to arrays too, but imho pretty well to slices ... and slices = arrays.

### CODE REVIEW

**Comment by schveiguy** [comment]
Sure, this is fine by me.

**Comment by WalterBright** [comment]
He seems stretched, not sliced!

**Comment by wilzbach** [comment]
> He seems stretched, not sliced!

We could slice him ;-)

image

(just a draft - not perfectly done)

**Comment by WalterBright** [comment]
I think you've hit on the right concept for the cartoon. D-Man's body is sliced and he looks down at it in shock/surprise!

**Comment by MartinNowak** [comment]
Let's go with the sliced one, looks good.

**Comment by AndrejMitrovic** [comment]
A D-man as a cook making really thin slices of some food would look cool. This one looks like a badly rendered image. :)

**Comment by MartinNowak** [comment]
How about slicing him in 3 parts so we have a clearer relation to the meaning of slicing, head, tail, and the actual slice content.
In case anyone know Learn You A Haskell's ListMonster, [listmonster](http://learnyouahaskell.com/starting-out#an-intro-to-lists).

**Comment by JackStouffer** [comment]
Hmm, that's actually an enemy from the Mario games. Wonder if they ran into copyright problems with that.

**Comment by wilzbach** [comment]
Closing this as I lost interest in pushing this. In case someone wants to pursue this, I started a repo with D-mans collected from all over the world: https://github.com/wilzbach/d-mans

**Pull request closed without merging**
