### PR TITLE
add link to tour.dlang.org

### PR DESCRIPTION
**Pull request by wilzbach**
Adds a link to tour.dlang.org.

Ping @stonemaster.

### CODE REVIEW

**Comment by CyberShadow** [comment]
HTTPS isn't working yet?

**Comment by CyberShadow** [comment]
So we start with this and promote to "Learn" link later?

**Comment by wilzbach** [comment]
> HTTPS isn't working yet?

Coming soon: https://github.com/stonemaster/dlang-tour/issues/45

> So we start with this and promote to "Learn" link later?

It was just an idea - I didn't know where exactly to add this ;-)

**Comment by wilzbach** [comment]
@CyberShadow I have made a [PR](https://github.com/stonemaster/dlang-tour/pull/79) that includes the getting started content.

Once that's in, we probably can replace the learn link?
(PR rebased)

**Comment by wilzbach** [comment]
ping @CyberShadow - so where do we stand here?

**Comment by CyberShadow** [comment]
Well, what's the state of your PR?

**Comment by wilzbach** [comment]
It awaits your approval ;-)

**Comment by CyberShadow** [comment]
I thought it was blocked by https://github.com/stonemaster/dlang-tour/pull/79 ?

**Comment by wilzbach** [comment]
Ah sorry - my bad. Will ping you once that's in

**Comment by wilzbach** [comment]
That was pretty quick - thanks @stonemaster :)

**Pull request merged**
