### PR TITLE
Add a paragraph about default construction

### PR DESCRIPTION
**Pull request by RazvanN7**
cc @wilzbach

### CODE REVIEW

**Comment by RazvanN7** [comment]
Yep, I had an error. Retag please.

**Comment by thewilsonator** [comment]
Done.

**Comment by RazvanN7** [comment]
Thanks!

**Comment by jmdavis** [comment]
Wait. This is wrong. Structs don't _have_ default constructors in D. They have an `init` value. And reading this PR, I don't think that you even meant default constructor. A default constructor is a constructor with no arguments that gets called when an object is constructed with no arguments, whereas I _think_ that what is being talked about here in the constructor that you automatically get for structs in D when you don't declare any. And even that isn't an actual constructor. IIRC no constructors show up in `allMembers` if you don't declare any. It's basically just using the constructor syntax for struct literals.

**Pull request merged**
