### PR TITLE
add __traits getBitfieldOffset and getBitfieldWidth

### PR DESCRIPTION
**Pull request by WalterBright**
Spec for https://github.com/dlang/dmd/pull/17043

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by WalterBright** [comment]
I clicked through all 578 instances of "traits" in the DAutoTest log and cannot find any errors.

**Comment by thewilsonator** [comment]
The DMD PR has not been merged yet, why would you expect the documentation `SPEC_RUNNABLE_EXAMPLE_COMPILE` to compile successfully ?

**Comment by thewilsonator** [comment]
```
---
struct S
{
    int a,b;
    int :2, c:3;
}

static assert(__traits(getBitfieldOffset, S.b) == 0);
static assert(__traits(getBitfieldOffset, S.c) == 2);

---
__stdin.d(4): Error: variable `__stdin.S.__anonBitField1` use -preview=bitfields for bitfield support
__stdin.d(4): Error: variable `__stdin.S.c` use -preview=bitfields for bitfield support
__stdin.d(7): Error: unrecognized trait `getBitfieldOffset`
__stdin.d(7):        while evaluating: `static assert(__traits(getBitfieldOffset, b) == 0)`
__stdin.d(8): Error: unrecognized trait `getBitfieldOffset`
__stdin.d(8):        while evaluating: `static assert(__traits(getBitfieldOffset, c) == 2)`
```
though I'm not sure how to add `-preview=bitfields` to a `SPEC_RUNNABLE_EXAMPLE_COMPILE`

**Comment by WalterBright** [comment]
Of course you're right, @thewilsonator . My beef is being unable to find the problem by reading the log file.

> though I'm not sure how to add -preview=bitfields to a SPEC_RUNNABLE_EXAMPLE_COMPILE

Grepping the doc files for "preview" shows a hackish way to do it, which I implemented

**Comment by thewilsonator** [comment]
As always, start at the bottom.

**Comment by WalterBright** [comment]
I did, and paged up a few times.

**Comment by thewilsonator** [comment]
This should not have been merged until the DMD PR has been accepted.

**Pull request merged**
