### PR TITLE
Rename {DMD,DRUNTIME,PHOBOS,VERSION}_STABLE -> _LATEST

### PR DESCRIPTION
**Pull request by wilzbach**
CC @MartinNowak @CyberShadow (follow-up to #1684)

### CODE REVIEW

**Comment by CyberShadow** [comment]
Why? Are all these renames achieving something?

**Comment by wilzbach** [comment]
Cleaning up the Makefile or in [Martin's words](https://github.com/dlang/dlang.org/pull/1684#issuecomment-307365531):

> Those should be named {DMD,DRUNTIME,PHOBOS}_LATEST, as they are a specific version, but not intended to be used as stable tool compiler.
In particular confusing since we have a STABLE_DMD_VER in that same makefile.

**Comment by CyberShadow** [comment]
OK, deferring to Martin then

**Comment by MartinNowak** [comment]
> Why? Are all these renames achieving something?

Yes, we want to introduce a new target named `release` for the installer builds, and use the correct term `latest` for the current one.
Also the term `stable` has 2 meanings in the current Makefile.

**Comment by wilzbach** [comment]
Rebased to the latest, greatest `posix.mak`. I am assuming that Martin needs to update his diff, so it probably make sense to wait for him here.

**Comment by wilzbach** [comment]
Rebased and this should be good to go now.
IIRC the nightly build server doesn't build the dlang.org anymore, so there's no risk at breaking it again.

**Comment by CyberShadow** [comment]
Build is failing.

**Comment by MartinNowak** [comment]
> Why? Are all these renames achieving something?

Clarifying terminology, the makefile is quite a mess atm.

**Pull request merged**
