### PR TITLE
[run-spec] Allow examples of the D spec to be runnable: spec_version

### PR DESCRIPTION
**Pull request by wilzbach**

### CODE REVIEW

**Comment by wilzbach** [comment]
@CyberShadow I hope it's easier to step-by-step review this as separate PRs.
My [tool](https://github.com/wilzbach/splitup-prs) is far from perfect, but it looks like it has done its job.

In general I was a quite liberate with adding `$(RUNNABLE_EXAMPLE)` as even playing with the compile error should be helpful to a reader.
In some cases
- I changed `test` -> `main` to allow execution
- As it's available as book, I try to add `import std.stdio` where it was missing (though it doesn't matter for dlang.org as `std.stdio` is always imported)
- Sometimes e.g. for unittests I added `$(RUNNABLE_EXAMPLE_ARGS ...)` - that's "new" way to clarify  arguments (there's also $(RUNNABLE_EXAMPLE_STDIN)`
- This isn't intended to be complete run, but I hope a good start with ~90% of the ones that are interesting to be runnable

**Comment by CyberShadow** [comment]
> @CyberShadow I hope it's easier to step-by-step review this as separate PRs.

Doesn't matter as long as the changes are split up into commits and all of them are uncontroversial.

> My tool is far from perfect, but it looks like it has done its job.

That looks redundant to me, but whatever fits your workflow :)

**Comment by CyberShadow** [comment]
https://github.com/dlang/dlang.org/pulls

OK, this is definitely not an improvement.

Let's please never do that again.

**Comment by CyberShadow** [comment]
@wilzbach Is it OK if I batch-close them and you submit one PR with one commit per file? I think I'm going to get RSI otherwise reviewing/merging these :)

**Comment by wilzbach** [comment]
> OK, this is definitely not an improvement.
> Let's please never do that again.

OK. Sorry. I can close everything and put into one PR?

**Comment by wilzbach** [comment]
> @wilzbach Is it OK if I batch-close them and you submit one PR with one commit per file? I think I'm going to get RSI otherwise reviewing/merging these :)

Yes of course. I can close myself. I wanted to make your life easier, not harder ...

**Comment by CyberShadow** [comment]
I think this approach would be better suited for things with lots of changes that require careful review and scrutiny, such as bulk automatic changes to source code that we're not sure are correct, but I understand that this isn't such a case. Even then, it's probably better to submit them incrementally, as reviewers may discover a problem with the overall technique or idea that would make the other PRs obsolete or needing an update.

**Comment by wilzbach** [comment]
> Yes of course. I can close myself. I wanted to make your life easier, not harder ...

It was an experiment - I should have asked before. Sorry.

-> https://github.com/dlang/dlang.org/pull/1754

**Pull request closed without merging**
