### PR TITLE
Remove # from tokens

### PR DESCRIPTION
**Pull request by dkorpel**
https://github.com/dlang/dmd/pull/15002#issuecomment-1499339001

### CODE REVIEW

**Comment by ibuclaw** [comment]
```
#line
```
?

**Comment by dkorpel** [comment]
That's defined by this rule:
```
$(GNAME SpecialTokenSequence):
    $(D # line) $(GLINK IntegerLiteral) $(GLINK Filespec)$(OPT) $(GLINK EndOfLine)
    $(D # line) $(D __LINE__) $(GLINK Filespec)$(OPT) $(GLINK EndOfLine)
```

**Comment by ibuclaw** [comment]
> That's defined by this rule:

Which includes the token `#`.

**Comment by dkorpel** [comment]
It includes the character `#`

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
