### PR TITLE
move glossary to spec

### PR DESCRIPTION
**Pull request by WalterBright**
It turns out that glossary.html is unreachable via the tables of contents. This fixes that by moving it into the spec. A glossary is useless if nobody can find it.

### CODE REVIEW

**Comment by CyberShadow** [comment]
> It turns out that glossary.html is unreachable via the tables of contents.

It's in the navigation ("Resources" menu), FWIW.

**Comment by CyberShadow** [comment]
Could you please add a redirect in `.htaccess`, so that old external links don't get broken?

**Comment by WalterBright** [comment]
@CyberShadow done

**Comment by CyberShadow** [comment]
Argh, the redirect is wrong.

**Pull request merged**
