### PR TITLE
Change Visual Studio 10 link to MSDN docs

### PR DESCRIPTION
**Pull request by NightmareX1337**
Changed links that redirected to Amazon with official Microsoft MSDN documentation
https://msdn.microsoft.com/en-us/library/dd831853(v=vs.100).aspx

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
That looks like an affiliate link. I'll have to ping @WalterBright if he's ok with the change.

**Comment by ZombineDev** [comment]
Can we upgrade the link to Visual Studio 2015 Community Edition, or VS C++ Build Tools 2015 (or maybe even https://www.visualstudio.com/en-us/news/releasenotes/vs15-relnotes)?

**Comment by andralex** [comment]
@AndrejMitrovic seems legit

**Comment by andralex** [comment]
@NightmareX1337 use 2015 per @ZombineDev ?

**Comment by NightmareX1337** [comment]
I can change PR to link to visualstudio.com as well..?

**Comment by andralex** [comment]
@NightmareX1337 fine with me

**Pull request merged**
