### PR TITLE
Update getLinkage

### PR DESCRIPTION
**Pull request by TurkeyMan**
Support of https://github.com/dlang/dmd/pull/8224

### CODE REVIEW

**Comment by TurkeyMan** [comment]
PR was merged...

**Comment by TurkeyMan** [comment]
What is problem?

**Comment by JinShil** [comment]
The problem is the Circle CI tests are failing.  It was fixed with https://github.com/dlang/dlang.org/pull/2371.  You just need to rebase.

**Comment by TurkeyMan** [comment]
Fixed.

**Pull request merged**
