### PR TITLE
Fix Issue 18765: - [Arrays] Docs need info on initialization of static array with element literal

### PR DESCRIPTION
**Pull request by RazvanMihaiPopa**
I simply added the information specified.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Thanks, Please update the _commit title_ to be "Fix Issue 18765: - [Arrays] Docs need info on initialization of static array with element literal"

**Comment by RazvanMihaiPopa** [comment]
is it okay now @thewilsonator ?

**Comment by thewilsonator** [comment]
Yes, you can now see that the bot picks up that it should close the related ticket.
I am not sure what is wrong with CircleCI though.

**Comment by RazvanMihaiPopa** [comment]
hmm yeah idk why.. what do u think i should do?

**Comment by RazvanMihaiPopa** [comment]
i pushed it again and i think its good now

**Pull request merged**
