### PR TITLE
Add OpenCollective backers to foundation/sponsors

### PR DESCRIPTION
**Pull request by wilzbach**
Preview:

image

### CODE REVIEW

**Comment by JackStouffer** [comment]
Can we add some CSS rules to bring the added elements in line with the rest of the site?

**Comment by wilzbach** [comment]
Not sure as it's essentially embedding this IFrame (https://opencollective.com/dlang/banner.html?limit=10&id=banner-iframe-8970&style={}) and they don't seem to allow CORS :/

They allow to inject custom style though via the URL parameter, but that doesn't seem to work for the text as (1) the use inline styles for the colors and (2) they only seem to allow a fixed set of css classes and `a` is one of the few allowed.

See also:

https://opencollective.com/dlang/banner.html?style={%22a%22:{%22color%22:%22orange%22},%22body%22:{%22color%22:%22blue%22}}

https://opencollective.com/widgets

**Comment by wilzbach** [comment]
Ping. I know that the design isn't ideal, but it's not on the front page and not hugely disturbing compared to the rest of the site, so imho we should merge this and whenever someone has time improve it.
We have done the same with the calendar..


CC @CyberShadow - would this be okay with you too?

**Comment by wilzbach** [comment]
Do you have troubles when opening https://opencollective.com/dlang/banner.html directly? Then we could just use the iframe directly without their loading injection.

**Comment by CyberShadow** [comment]
No, that works perfectly fine, even with JavaScript disabled.

**Comment by JackStouffer** [comment]
Works fine on Firefox an Safari on macOS.

**Comment by wilzbach** [comment]
> No, that works perfectly fine, even with JavaScript disabled.

Hmm, I would prefer that solution too, but the problem here is that the height of the iframe is dynamic and CORS restrictions prevent us from accessing it and checking for the height.

There are a few suggestions on SO, but they are all not really pretty and often require access to the source:

https://stackoverflow.com/questions/5589756/is-there-a-cross-domain-iframe-height-auto-resizer-that-works

> Works fine on Firefox an Safari on macOS.

And Chrome + Firefox on my Linux machine too.

**Pull request merged**
