### PR TITLE
Fix example on the front page

### PR DESCRIPTION
**Pull request by 9il**
`.sort` is deprecated property. In the same time `.sort()` looks weird.

### CODE REVIEW

**Comment by JackStouffer** [comment]
I wish the `sort` property would get removed some day soon.

LGTM

**Comment by CyberShadow** [comment]
> In the same time .sort() looks weird.

IMHO it's less weird than scaring people into thinking that they must always specify a sort predicate.

**Comment by 9il** [comment]
> IMHO it's less weird than scaring people into thinking that they must always specify a sort predicate.

Reverse order? `.sort!((a, b) => a > b)`

**Comment by quickfur** [comment]
LGTM.

**Comment by adamdruppe** [comment]
@9il Add the comment about reverse order and I'll merge this too.

**Comment by 9il** [comment]
> @9il Add the comment about reverse order and I'll merge this too.

done

**Comment by CyberShadow** [comment]
I think you need to also update the example hash in `js/run-main-website.js` so that the input is carried along. (See the commentary at the top of `js/run.js` for instructions.)

**Comment by 9il** [comment]
> I think you need to also update the example hash in js/run-main-website.js so that the input is carried along. (See the commentary at the top of js/run.js for instructions.)

done

**Comment by CyberShadow** [comment]
Thanks

**Pull request merged**
