### PR TITLE
Orgs using D: Add Ecratum

### PR DESCRIPTION
**Pull request by wilzbach**
resubmission of #1381 

CC @llaine

@CyberShadow It seems we use `150x75` for the frontpage, but here we use `200x100`. Sorry about that & corrected.

### CODE REVIEW

**Comment by llaine** [comment]
It's totally fine for me like this!

**Comment by claudiug** [comment]
@wilzbach any news with this one. I would love to have the logo there. Plus I guess will be a blog post maybe for marketing :)

**Comment by wilzbach** [comment]
> @wilzbach any news with this one. I would love to have the logo there.

I don't have merge rights here. Thanks @CyberShadow!
(it will now automatically be deployed in the next minutes)

>  Plus I guess will be a blog post maybe for marketing :)

I am looking forward too it :)

**Comment by llaine** [comment]
@wilzbach Thank you for this :tada: ! I notice that the link is broken also for the hiring ... `http//` instead of `http://` do you think you can do a quick hot fix ? :)

**Comment by CyberShadow** [comment]
Someone must have cursed this page with the curse of bad and broken links... https://github.com/dlang/dlang.org/pull/1419

**Comment by wilzbach** [comment]
btw @llaine the hiring link is thought to be for "D jobs" - I couldn't spot any open position there. I heard that you plan to transition parts of your infrastructure from Ruby to D, which is very nice to hear.
Do you plan to update your page once this is official? Otherwise it might be a bit confusing for D developers looking for jobs ;-)

**Pull request merged**
