### PR TITLE
Add DConf submission deadline notice

### PR DESCRIPTION
**Pull request by mdparker**
Didn't view locally yet, because the build kept hanging in my Linux VM . I'll check the autotester link when it's ready.

### CODE REVIEW

**Comment by mdparker** [comment]
Damn. It's broken.

**Comment by mdparker** [comment]
Okay. The local build finally completed and nothing is broken. Looks ok on the autotester too.

**Comment by JinShil** [comment]
image

Looks a little weird with the "From : by" text.

**Comment by wilzbach** [comment]
It's not broken, DAutoTest just disables the macros, s.t. no random diff changes occur on a PR.

**Comment by wilzbach** [comment]
> It's not broken, DAutoTest just disables the macros, s.t. no random diff changes occur on a PR.

https://github.com/dlang/dlang.org/pull/2234

**Comment by wilzbach** [comment]
image

It's a bit tiny and hard to see. Maybe I can quickly throw something together, but I think in the interest of time we should definitely merge this.

Thanks @mdparker!

**Pull request merged**
